// AUTO-GENERATED — DO NOT EDIT
// Source: packages/p1-starter-components/scripts/generate-catalog.mjs
// Run `pnpm registry:generate` to refresh after adding or removing a block.

// Kept free of component imports — see catalog.generated.tsx's previewComponents
// for why. Puck field metadata per block — name, display type, and default
// value — for the catalog's block detail page. Parsed from each block's own
// `fields` and `defaultProps`, so it can't drift from what the component accepts.
export const blockProps: Record<string, { name: string; type: string; default: string }[]> = {
  'accordion': [{"name":"heading","type":"string","default":"\"The details\""},{"name":"align","type":"\"left\" | \"center\"","default":"\"left\""},{"name":"items","type":"array","default":"array"}],
  'announcement': [{"name":"text","type":"string","default":"\"Something new just launched — take a loo…\""},{"name":"linkLabel","type":"string","default":"\"Read the announcement →\""},{"name":"tone","type":"\"accent\" | \"yellow\" | \"dark\" | \"gradient\"","default":"\"accent\""},{"name":"align","type":"\"center\" | \"left\"","default":"\"center\""}],
  'article-header': [{"name":"category","type":"string","default":"\"Engineering\""},{"name":"title","type":"string","default":"\"What a year of shipping on Multidev taug…\""},{"name":"standfirst","type":"string","default":"\"A behind-the-scenes look at how the team…\""},{"name":"authorName","type":"string","default":"\"Jordan Ellis\""},{"name":"authorAvatar","type":"string","default":"P1_ASSETS.AVATAR"},{"name":"date","type":"string","default":"\"April 18, 2026\""},{"name":"readTime","type":"string","default":"\"6 min read\""},{"name":"align","type":"\"left\" | \"center\"","default":"\"left\""},{"name":"rule","type":"\"on\" | \"off\"","default":"\"on\""}],
  'button': [{"name":"label","type":"string","default":"\"Get started\""},{"name":"href","type":"string","default":"\"#\""},{"name":"variant","type":"\"primary\" | \"secondary\" | \"yellow\" | \"purple\"","default":"\"primary\""},{"name":"align","type":"\"left\" | \"center\"","default":"\"left\""}],
  'callout': [{"name":"variant","type":"\"note\" | \"info\" | \"tip\" | \"warning\"","default":"\"tip\""},{"name":"title","type":"string","default":"\"Try this\""},{"name":"body","type":"string","default":"\"Make “preview first” the default. Share …\""}],
  'card-grid': [{"name":"heading","type":"string","default":"\"Customer stories\""},{"name":"columns","type":"\"2\" | \"3\" | \"4\"","default":"\"3\""},{"name":"items","type":"array","default":"[\n      { title: \"Northwind\", subtitle: …"}],
  'columns': [{"name":"distribution","type":"\"1:1\" | \"2:1\" | \"1:2\" | \"1:1:1\" | \"1:1:1:1\"","default":"\"1:1\""},{"name":"gap","type":"\"tight\" | \"regular\" | \"wide\"","default":"\"regular\""},{"name":"valign","type":"\"top\" | \"center\" | \"stretch\"","default":"\"top\""},{"name":"tone","type":"\"none\" | \"light\"","default":"\"none\""},{"name":"col1","type":"slot","default":"array"},{"name":"col2","type":"slot","default":"array"},{"name":"col3","type":"slot","default":"array"},{"name":"col4","type":"slot","default":"array"}],
  'comparison-table': [{"name":"eyebrow","type":"string","default":"\"Compare\""},{"name":"heading","type":"string","default":"\"Find the plan that fits.\""},{"name":"subtitle","type":"string","default":"\"Every plan includes the core WebOps work…\""},{"name":"columns","type":"string","default":"\"Starter\\nTeam\\nEnterprise\""},{"name":"featured","type":"\"none\" | \"1\" | \"2\" | \"3\" | \"4\"","default":"\"2\""},{"name":"rows","type":"array","default":"array"}],
  'container': [{"name":"content","type":"slot","default":"array"},{"name":"tone","type":"\"none\" | \"light\" | \"white\"","default":"\"light\""},{"name":"pad","type":"\"compact\" | \"regular\" | \"spacious\"","default":"\"regular\""},{"name":"maxWidth","type":"\"narrow\" | \"standard\" | \"wide\" | \"full\"","default":"\"standard\""},{"name":"align","type":"\"left\" | \"center\"","default":"\"left\""},{"name":"radius","type":"\"none\" | \"soft\" | \"round\"","default":"\"soft\""}],
  'cta': [{"name":"eyebrow","type":"string","default":"\"\""},{"name":"title","type":"string","default":"\"Ready to ship faster?\""},{"name":"subtitle","type":"string","default":"\"Start a free trial — no credit card, no …\""},{"name":"buttonLabel","type":"string","default":"\"Start free trial\""},{"name":"secondaryLabel","type":"string","default":"\"\""},{"name":"layout","type":"\"centered\" | \"split\"","default":"\"centered\""},{"name":"align","type":"\"left\" | \"center\"","default":"\"center\""},{"name":"tone","type":"\"yellow\" | \"accent\" | \"dark\" | \"light\" | \"gradient\" | \"outline\"","default":"\"yellow\""},{"name":"decoration","type":"\"none\" | \"glow\" | \"dots\"","default":"\"none\""},{"name":"corners","type":"\"square\" | \"soft\" | \"round\"","default":"\"round\""},{"name":"padding","type":"\"compact\" | \"regular\" | \"spacious\"","default":"\"regular\""}],
  'divider': [{"name":"style","type":"\"solid\" | \"dashed\" | \"dots\"","default":"\"solid\""},{"name":"spacing","type":"\"small\" | \"medium\" | \"large\"","default":"\"medium\""}],
  'embed': [{"name":"kind","type":"\"video\" | \"social\" | \"map\" | \"generic\"","default":"\"video\""},{"name":"url","type":"string","default":"\"https://youtube.com/watch?v=demo\""},{"name":"title","type":"string","default":"\"Inside a Pantheon deploy — start to Live…\""},{"name":"ratio","type":"\"16 / 9\" | \"4 / 3\" | \"1 / 1\"","default":"\"16 / 9\""},{"name":"caption","type":"string","default":"\"\""},{"name":"width","type":"\"contained\" | \"wide\"","default":"\"wide\""}],
  'faq': [{"name":"heading","type":"string","default":"\"Frequently asked questions\""},{"name":"items","type":"array","default":"array"}],
  'feature-media': [{"name":"eyebrow","type":"string","default":"\"How it works\""},{"name":"title","type":"string","default":"\"Designed around the way you work.\""},{"name":"body","type":"string","default":"\"Move from idea to published in a few cli…\""},{"name":"bullets","type":"array","default":"array"},{"name":"buttonLabel","type":"string","default":"\"See how it works →\""},{"name":"imageSrc","type":"string","default":"P1_ASSETS.LANDSCAPE"},{"name":"mediaSide","type":"\"right\" | \"left\"","default":"\"right\""},{"name":"tone","type":"\"white\" | \"light\" | \"dark\"","default":"\"white\""}],
  'features': [{"name":"subtitle","type":"string","default":"\"Why teams choose us\""},{"name":"heading","type":"string","default":"\"Everything you need, in one place.\""},{"name":"cards","type":"array","default":"array"},{"name":"columns","type":"\"2\" | \"3\" | \"4\"","default":"\"3\""},{"name":"colorScheme","type":"\"brand mix\" | \"light\" | \"purple\" | \"dark\" | \"outline\"","default":"\"brand mix\""},{"name":"corners","type":"\"sharp\" | \"soft\" | \"round\"","default":"\"round\""},{"name":"depth","type":"\"flat\" | \"subtle\" | \"raised\"","default":"\"flat\""},{"name":"cardAlign","type":"\"left\" | \"center\"","default":"\"left\""},{"name":"sectionBg","type":"\"light\" | \"white\" | \"dark\" | \"none\"","default":"\"light\""}],
  'figure': [{"name":"src","type":"string","default":"P1_ASSETS.LANDSCAPE"},{"name":"alt","type":"string","default":"\"The team reviewing a preview together\""},{"name":"caption","type":"string","default":"\"The team reviews a preview link before a…\""},{"name":"credit","type":"string","default":"\"Photo — Pantheon\""},{"name":"ratio","type":"\"16 / 9\" | \"3 / 2\" | \"4 / 3\" | \"1 / 1\" | \"21 / 9\"","default":"\"3 / 2\""},{"name":"width","type":"\"contained\" | \"wide\" | \"full bleed\"","default":"\"wide\""},{"name":"radius","type":"\"none\" | \"soft\" | \"round\"","default":"\"soft\""},{"name":"treatment","type":"\"color\" | \"b&w\"","default":"\"color\""}],
  'footer': [{"name":"logo","type":"string","default":"\"Pantheon\""},{"name":"tagline","type":"string","default":"\"The WebOps platform for WordPress and Dr…\""},{"name":"columns","type":"array","default":"array"},{"name":"newsletter","type":"\"on\" | \"off\"","default":"\"on\""},{"name":"newsletterTitle","type":"string","default":"\"Ship better, every week.\""},{"name":"newsletterButton","type":"string","default":"\"Subscribe\""},{"name":"social","type":"\"on\" | \"off\"","default":"\"on\""},{"name":"legal","type":"\"on\" | \"off\"","default":"\"on\""},{"name":"copyright","type":"string","default":"\"© 2026 Pantheon Systems, Inc.\""},{"name":"legalLinks","type":"string","default":"\"Privacy\\nTerms\\nSecurity\\nStatus\""},{"name":"tone","type":"\"dark\" | \"accent\" | \"light\"","default":"\"dark\""}],
  'gallery': [{"name":"heading","type":"string","default":"\"From the field\""},{"name":"layout","type":"\"grid\" | \"masonry\" | \"filmstrip\" | \"carousel\"","default":"\"grid\""},{"name":"columns","type":"\"2\" | \"3\" | \"4\"","default":"\"3\""},{"name":"gap","type":"\"tight\" | \"regular\" | \"wide\"","default":"\"regular\""},{"name":"ratio","type":"\"1 / 1\" | \"4 / 3\" | \"3 / 2\" | \"16 / 9\"","default":"\"4 / 3\""},{"name":"radius","type":"\"none\" | \"soft\" | \"round\"","default":"\"soft\""},{"name":"captions","type":"\"off\" | \"on\"","default":"\"off\""},{"name":"images","type":"array","default":"[\n      { src: P1_ASSETS.LANDSCAPE, capt…"}],
  'header': [{"name":"logo","type":"string","default":"\"Pantheon\""},{"name":"links","type":"array","default":"array"},{"name":"navAlign","type":"\"left\" | \"center\" | \"right\"","default":"\"center\""},{"name":"showSearch","type":"\"off\" | \"on\"","default":"\"on\""},{"name":"ctaLabel","type":"string","default":"\"Start for free\""},{"name":"ctaStyle","type":"\"primary\" | \"yellow\" | \"purple\" | \"outline\" | \"none\"","default":"\"primary\""},{"name":"tone","type":"\"white\" | \"light\" | \"dark\"","default":"\"white\""},{"name":"border","type":"\"on\" | \"off\"","default":"\"on\""},{"name":"sticky","type":"\"off\" | \"on\"","default":"\"off\""}],
  'heading': [{"name":"text","type":"string","default":"\"A heading to anchor the section\""},{"name":"level","type":"\"H1\" | \"H2\" | \"H3\" | \"H4\"","default":"\"H2\""},{"name":"align","type":"\"left\" | \"center\"","default":"\"left\""}],
  'hero': [{"name":"eyebrow","type":"string","default":"\"New — now available\""},{"name":"title","type":"string","default":"\"Your big idea, beautifully online.\""},{"name":"description","type":"string","default":"\"A flexible starting point for your next …\""},{"name":"primaryLabel","type":"string","default":"\"Start free trial\""},{"name":"secondaryLabel","type":"string","default":"\"Book a demo →\""},{"name":"imageSrc","type":"string","default":"P1_ASSETS.LANDSCAPE"},{"name":"tone","type":"\"accent\" | \"dark\" | \"light\"","default":"\"accent\""},{"name":"layout","type":"\"split\" | \"full image\" | \"text only\"","default":"\"split\""},{"name":"imageSide","type":"\"right\" | \"left\"","default":"\"right\""},{"name":"imageFill","type":"\"card\" | \"flush\"","default":"\"card\""},{"name":"splitRatio","type":"\"even\" | \"copy-wide\" | \"image-wide\"","default":"\"even\""},{"name":"align","type":"\"left\" | \"center\" | \"right\"","default":"\"left\""},{"name":"overlay","type":"\"none\" | \"scrim\" | \"gradient down\" | \"gradient right\"","default":"\"gradient right\""},{"name":"overlayStrength","type":"\"light\" | \"medium\" | \"heavy\"","default":"\"medium\""},{"name":"knockout","type":"\"off\" | \"on\"","default":"\"off\""}],
  'image': [{"name":"src","type":"string","default":"P1_ASSETS.LANDSCAPE"},{"name":"alt","type":"string","default":"\"Editorial photograph\""},{"name":"width","type":"\"contained\" | \"full bleed\"","default":"\"contained\""},{"name":"ratio","type":"\"16 / 9\" | \"4 / 3\" | \"1 / 1\" | \"3 / 2\" | \"21 / 9\"","default":"\"16 / 9\""},{"name":"fit","type":"\"cover\" | \"contain\" | \"fill\"","default":"\"cover\""},{"name":"position","type":"\"center\" | \"top\" | \"bottom\" | \"left\" | \"right\"","default":"\"center\""},{"name":"radius","type":"\"none\" | \"soft\" | \"round\"","default":"\"soft\""},{"name":"treatment","type":"\"color\" | \"b&w\"","default":"\"color\""}],
  'lead-capture': [{"name":"heading","type":"string","default":"\"Stay in the loop.\""},{"name":"subtitle","type":"string","default":"\"Occasional updates, straight to your inb…\""},{"name":"placeholder","type":"string","default":"\"you@company.com\""},{"name":"buttonLabel","type":"string","default":"\"Subscribe\""},{"name":"note","type":"string","default":"\"No spam. Unsubscribe anytime.\""},{"name":"tone","type":"\"light\" | \"accent\" | \"dark\" | \"yellow\"","default":"\"accent\""},{"name":"layout","type":"\"inline\" | \"stacked\"","default":"\"inline\""}],
  'list': [{"name":"items","type":"array","default":"array"},{"name":"style","type":"\"bullet\" | \"numbered\" | \"check\"","default":"\"bullet\""}],
  'logos': [{"name":"heading","type":"string","default":"\"Featured in\""},{"name":"style","type":"\"mono\" | \"color\"","default":"\"mono\""},{"name":"height","type":"\"small\" | \"medium\" | \"large\"","default":"\"medium\""},{"name":"logos","type":"array","default":"array"}],
  'paragraph': [{"name":"text","type":"richtext","default":"\"This is a paragraph. Use it to expand on…\""},{"name":"style","type":"\"body\" | \"lead\"","default":"\"body\""},{"name":"size","type":"\"small\" | \"regular\" | \"large\"","default":"\"regular\""},{"name":"align","type":"\"left\" | \"center\"","default":"\"left\""}],
  'pricing': [{"name":"eyebrow","type":"string","default":"\"Pricing\""},{"name":"heading","type":"string","default":"\"Plans that scale with your portfolio.\""},{"name":"subtitle","type":"string","default":"\"Start free. Upgrade when your team is re…\""},{"name":"tiers","type":"array","default":"array"}],
  'pull-quote': [{"name":"quote","type":"richtext","default":"\"The best workflow is the one your whole …\""},{"name":"cite","type":"string","default":"\"Jordan Ellis, Operations Lead\""},{"name":"accent","type":"\"yellow rule\" | \"quote mark\" | \"none\"","default":"\"yellow rule\""},{"name":"align","type":"\"center\" | \"left\"","default":"\"center\""}],
  'quote': [{"name":"quote","type":"richtext","default":"\"The measure of intelligence is the abili…\""},{"name":"attribution","type":"string","default":"\"Albert Einstein\""},{"name":"scale","type":"\"standard\" | \"display\"","default":"\"standard\""}],
  'rich-text': [{"name":"content","type":"richtext","default":"\"<p>A year ago, shipping a change meant a…\""},{"name":"measure","type":"\"narrow\" | \"standard\" | \"wide\"","default":"\"standard\""},{"name":"size","type":"\"regular\" | \"large\"","default":"\"regular\""},{"name":"dropCap","type":"\"off\" | \"on\"","default":"\"off\""}],
  'spacer': [{"name":"size","type":"\"xs\" | \"sm\" | \"md\" | \"lg\" | \"xl\"","default":"\"md\""}],
  'stats': [{"name":"tone","type":"\"light\" | \"dark\"","default":"\"light\""},{"name":"items","type":"array","default":"array"}],
  'steps': [{"name":"eyebrow","type":"string","default":"\"How it works\""},{"name":"heading","type":"string","default":"\"Ship in three steps.\""},{"name":"items","type":"array","default":"array"},{"name":"tone","type":"\"white\" | \"light\" | \"dark\"","default":"\"light\""}],
  'tabs': [{"name":"heading","type":"string","default":"\"Everything in one workflow\""},{"name":"align","type":"\"left\" | \"center\"","default":"\"left\""},{"name":"tabs","type":"array","default":"array"}],
  'team-grid': [{"name":"eyebrow","type":"string","default":"\"The team\""},{"name":"heading","type":"string","default":"\"People behind the platform.\""},{"name":"columns","type":"\"2\" | \"3\" | \"4\"","default":"\"3\""},{"name":"shape","type":"\"circle\" | \"rounded\"","default":"\"circle\""},{"name":"tone","type":"\"white\" | \"light\"","default":"\"white\""},{"name":"members","type":"array","default":"[\n      { name: \"Jordan Ellis\", role: \"H…"}],
  'testimonial': [{"name":"quote","type":"string","default":"\"The team was up and running in a day, an…\""},{"name":"name","type":"string","default":"\"Jordan Ellis\""},{"name":"role","type":"string","default":"\"Operations Lead\""},{"name":"avatarSrc","type":"string","default":"P1_ASSETS.AVATAR"},{"name":"layout","type":"\"centered\" | \"card\" | \"large\"","default":"\"centered\""},{"name":"tone","type":"\"light\" | \"white\" | \"accent\" | \"dark\"","default":"\"light\""}],
  'timeline': [{"name":"eyebrow","type":"string","default":"\"Our story\""},{"name":"heading","type":"string","default":"\"How we got here.\""},{"name":"layout","type":"\"vertical\" | \"alternating\"","default":"\"vertical\""},{"name":"tone","type":"\"white\" | \"light\"","default":"\"white\""},{"name":"items","type":"array","default":"array"}],
};
