// Kebab-case registry name → allBlocks key. Kept free of component imports so
// the catalog page can list preview names without pulling in every block's CSS,
// which would otherwise override the site chrome (.p1-header, .p1-footer).
// Three names deviate from the simple pascal pattern (logos, features, cta).
export const NAME_TO_KEY = {
  accordion: 'AccordionBlock',
  announcement: 'AnnouncementBlock',
  'article-header': 'ArticleHeaderBlock',
  button: 'ButtonBlock',
  callout: 'CalloutBlock',
  'card-grid': 'CardGridBlock',
  'comparison-table': 'ComparisonTableBlock',
  columns: 'ColumnsBlock',
  container: 'ContainerBlock',
  cta: 'CtaBannerBlock',
  divider: 'DividerBlock',
  embed: 'EmbedBlock',
  faq: 'FaqBlock',
  'feature-media': 'FeatureMediaBlock',
  features: 'FeatureCardsBlock',
  figure: 'FigureBlock',
  footer: 'FooterBlock',
  gallery: 'GalleryBlock',
  header: 'HeaderBlock',
  heading: 'HeadingBlock',
  hero: 'HeroBlock',
  image: 'ImageBlock',
  'lead-capture': 'LeadCaptureBlock',
  list: 'ListBlock',
  logos: 'LogoCloudBlock',
  paragraph: 'ParagraphBlock',
  pricing: 'PricingBlock',
  'pull-quote': 'PullQuoteBlock',
  quote: 'QuoteBlock',
  'rich-text': 'RichTextBlock',
  spacer: 'SpacerBlock',
  stats: 'StatsBlock',
  steps: 'StepsBlock',
  tabs: 'TabsBlock',
  'team-grid': 'TeamGridBlock',
  testimonial: 'TestimonialBlock',
  timeline: 'TimelineBlock',
} as const;

export const previewNames = Object.keys(NAME_TO_KEY);
