/**
 * Query type definitions.
 *
 * A query defines WHAT to retrieve from a datasource —
 * filters, sort, pagination. Stored at `_registry/queries/{name}`.
 * The View system references queries, not datasources directly.
 */

export interface QuerySortField {
  field: string;
  direction: 'asc' | 'desc';
}

export interface QuerySnapshot {
  name: string;
  description?: string;
  datasource: string;
  sort: QuerySortField[];
  defaultLimit: number;
  maxLimit: number;
  includeMetadata: boolean;
  includeSnapshot: boolean;
  autoGenerated: boolean;
  version: number;
}

export function parseQuerySnapshot(value: unknown): QuerySnapshot {
  if (value === null || typeof value !== 'object') {
    throw new Error('QuerySnapshot: expected an object');
  }
  const obj = value as Record<string, unknown>;
  if (typeof obj.name !== 'string') {
    throw new Error('QuerySnapshot: name must be a string');
  }
  if (obj.description !== undefined && typeof obj.description !== 'string') {
    throw new Error('QuerySnapshot: description must be a string');
  }
  if (typeof obj.datasource !== 'string') {
    throw new Error('QuerySnapshot: datasource must be a string');
  }
  if (!Array.isArray(obj.sort)) {
    throw new Error('QuerySnapshot: sort must be an array');
  }
  for (const s of obj.sort as unknown[]) {
    if (typeof s !== 'object' || s === null) {
      throw new Error('QuerySnapshot: each sort entry must be an object');
    }
    const entry = s as Record<string, unknown>;
    if (typeof entry.field !== 'string' || (entry.direction !== 'asc' && entry.direction !== 'desc')) {
      throw new Error('QuerySnapshot: each sort entry must have a string field and direction "asc" or "desc"');
    }
  }
  if (typeof obj.defaultLimit !== 'number') {
    throw new Error('QuerySnapshot: defaultLimit must be a number');
  }
  if (typeof obj.maxLimit !== 'number') {
    throw new Error('QuerySnapshot: maxLimit must be a number');
  }
  if (typeof obj.includeMetadata !== 'boolean') {
    throw new Error('QuerySnapshot: includeMetadata must be a boolean');
  }
  if (typeof obj.includeSnapshot !== 'boolean') {
    throw new Error('QuerySnapshot: includeSnapshot must be a boolean');
  }
  if (typeof obj.autoGenerated !== 'boolean') {
    throw new Error('QuerySnapshot: autoGenerated must be a boolean');
  }
  if (typeof obj.version !== 'number') {
    throw new Error('QuerySnapshot: version must be a number');
  }
  return value as QuerySnapshot;
}

export interface QueryResultItem {
  documentId: string;
  path: string;
  createdAt: string;
  templateVersion?: number;
  metadata?: Record<string, unknown>;
  snapshot?: Record<string, unknown>;
}

export interface ExecuteQueryResult {
  items: QueryResultItem[];
  totalCount: number;
  returnedCount: number;
  query: {
    name: string;
    datasource: string;
    sortedBy: string;
    appliedLimit: number;
    appliedOffset: number;
  };
}

