#!/usr/bin/env bash
# Fails the build — PR CI hard gates and the publish workflow both run this —
# if any public package's tarball would ship internal
# architecture: Jira ticket refs, backend implementation details (storage
# engine, CRDT, compute primitive), or real hostnames.
# See PCC-3819 — every term here was found leaking into a published tarball.
#
# Packs each non-private package exactly as `npm publish` would (respecting
# the "files" allowlist and npm's forced inclusion of README/package.json),
# then greps the real tarball contents rather than the source tree, so a
# leak that only shows up post-build (e.g. in a .d.ts) is still caught.
#
# FAIL CLOSED: an unreadable tarball, an unexpected layout, or a "files"
# entry with nothing behind it is an error, never a pass. `npm pack` does
# not run `prepublishOnly` (only `npm publish` does), so a package whose
# publish artifacts are generated by a build step — create-p1-starter-kit's
# template/ — packs "successfully" but near-empty if the build hasn't run;
# without the allowlist check that surface would go out unscanned.
#
# Usage: check-npm-leaks.sh              (run from repo root, after the build step)
#        check-npm-leaks.sh --self-test  (verify detection against fixtures; run
#                                         this first in CI so a regression in this
#                                         script fails the build, not the check)
set -euo pipefail

# Case-insensitive: the expanded codename is prose and can appear in any casing.
# The bare `CCR` service name is deliberately NOT banned. It names a service
# without revealing how it works, and it is already public in the default
# `ccr.p1.pantheon.io` hostname every unconfigured consumer's SDK calls. What
# must not ship is the architecture behind it — see CS_PATTERN.
CI_PATTERN='Collaborative[[:space:]]+(Content[[:space:]]+Repository|State[[:space:]]+System)'
# Case-sensitive: `PCC-1234` and `Postgres`/`CRDT`/`Durable Object` never
# legitimately appear lowercased, and a case-insensitive `cloudflare` throws a
# false positive on generic public references (e.g. the built-in `cloudflare:*`
# Workers module namespace in a starter-kit eslint config).
# Known limitation: a term embedded lowercase in an identifier evades this
# (css-client shipped a `crdtState` field that way until it was removed in
# PCC-3819) — widening the patterns means an exemption mechanism, which this
# script deliberately lost.
CS_PATTERN='PCC-[0-9]+|\bPostgres\b|\bCRDT\b|Durable Object|\.workers\.dev'
# `Cloudflare` is deliberately not a global term: css-client, p1-next-sdk,
# puck-css, p1-ai-chat, and p1-content-validator have no legitimate reason to
# name it, but p1-media (p1-media-r2) is an intentionally Cloudflare-R2-backed
# plugin and says so in its own public description — banning the word there
# would just force an endless allowlist. `.workers.dev` (a real, discoverable
# hostname) is still banned everywhere, p1-media included.
# Exact package names, space-separated.
CLOUDFLARE_EXEMPT_PACKAGES='@pantheon-systems/p1-media'

# Everything below leans on jq; process substitution swallows its exit status,
# so a missing jq would silently no-op the files-allowlist check.
command -v jq >/dev/null 2>&1 || { echo '::error::jq is required'; exit 1; }

# Scans one extracted tarball. $1 = extracted contents dir (must contain
# package/), $2 = package name, $3 = the case-sensitive pattern for this
# package. Returns 0 clean, 1 on any leak or structural problem.
scan_extracted() {
  local extract_dir=$1 name=$2 cs_pattern=$3
  local pkg_root="$extract_dir/package"

  # Fail closed: `grep -r` over a missing directory finds nothing, and
  # "nothing found" must never be reachable by scanning the wrong place.
  if [ ! -f "$pkg_root/package.json" ]; then
    echo "::error::${name}: extracted tarball has no package/package.json — layout changed or extraction failed; refusing to report clean"
    return 1
  fi

  local candidate_files
  candidate_files=$(printf '%s\n%s\n' \
    "$(grep -rliE "$CI_PATTERN" "$pkg_root" 2>/dev/null || true)" \
    "$(grep -rlE "$cs_pattern" "$pkg_root" 2>/dev/null || true)" \
    | sed '/^$/d' | sort -u)

  local scan_failed=0
  if [ -n "$candidate_files" ]; then
    local f lines
    while IFS= read -r f; do
      lines=$( { grep -niE "$CI_PATTERN" "$f" || true; grep -nE "$cs_pattern" "$f" || true; } )
      if [ -n "$lines" ]; then
        scan_failed=1
        echo "::error file=${f}::${name} tarball leaks internal architecture — see .github/scripts/check-npm-leaks.sh"
        echo "$lines" | sed 's/^/    /'
      fi
    done <<< "$candidate_files"
  fi
  return "$scan_failed"
}

# Packs and scans one package directory. Returns 0 clean, 1 otherwise.
check_package_dir() {
  local pkg_dir=$1
  local pkg_json="${pkg_dir%/}/package.json"
  [ -f "$pkg_json" ] || return 0

  local is_private
  is_private=$(jq -r '.private // false' "$pkg_json")
  [ "$is_private" = "true" ] && return 0

  local name
  name=$(jq -r '.name' "$pkg_json")

  local cs_pattern="$CS_PATTERN" exempt=''
  local ex
  for ex in $CLOUDFLARE_EXEMPT_PACKAGES; do
    [ "$ex" = "$name" ] && exempt=1
  done
  [ -n "$exempt" ] || cs_pattern="${cs_pattern}|Cloudflare"

  echo "Checking ${name}..."
  checked_count=$((checked_count + 1))
  local tmp_dir tarball
  tmp_dir=$(mktemp -d)
  if ! tarball=$(cd "$pkg_dir" && npm pack --silent --pack-destination "$tmp_dir" 2>&1); then
    echo "::error::${name}: npm pack failed — refusing to report clean"
    echo "$tarball" | sed 's/^/    /'
    rm -rf "$tmp_dir"
    return 1
  fi

  local extract_dir="${tmp_dir}/contents"
  mkdir -p "$extract_dir"
  if ! tar -xzf "${tmp_dir}/${tarball}" -C "$extract_dir"; then
    echo "::error::${name}: could not extract ${tarball} — refusing to report clean"
    rm -rf "$tmp_dir"
    return 1
  fi

  local pkg_failed=0

  # Every glob-free "files" entry must actually be in the tarball. npm pack
  # silently omits a missing entry, so a package whose publish content is
  # build-generated (create-p1-starter-kit's template/) would otherwise scan
  # near-empty here and then publish ~100 unscanned files, because the real
  # `npm publish` runs `prepublishOnly` and regenerates it. Glob entries
  # (e.g. `src/**/*.css`) are skipped — matching npm's glob semantics in
  # shell is a bug farm, and every generated directory here is a plain path.
  local listing entry
  listing=$(tar -tzf "${tmp_dir}/${tarball}")
  local entry_re
  while IFS= read -r entry; do
    case "$entry" in *'*'*|*'?'*|*'['*) continue ;; esac
    entry="${entry%/}"
    entry_re=$(printf '%s\n' "$entry" | sed -e 's/[][\.*^$]/\\&/g')
    # Herestring, not a pipe: `grep -q` exits on first match, and under
    # pipefail a still-writing printf then turns a FOUND entry into exit 141.
    if ! grep -q "^package/${entry_re}\(/\|\$\)" <<< "$listing"; then
      pkg_failed=1
      echo "::error::${name}: \"files\" entry '${entry}' is missing from the packed tarball — its content was not built, so it cannot be scanned (and npm publish WOULD ship it after prepublishOnly regenerates it). Build first."
    fi
  done < <(jq -r '.files[]?' "$pkg_json")

  # Filenames are public too — npmjs.com renders the full tarball listing —
  # so a clean file named PCC-1234-notes.txt still leaks.
  local name_hits
  name_hits=$( { grep -iE "$CI_PATTERN" <<< "$listing" || true; grep -E "$cs_pattern" <<< "$listing" || true; } | sort -u)
  if [ -n "$name_hits" ]; then
    pkg_failed=1
    echo "::error::${name}: tarball FILENAMES leak internal terms — npmjs.com shows the file listing publicly"
    echo "$name_hits" | sed 's/^/    /'
  fi

  scan_extracted "$extract_dir" "$name" "$cs_pattern" || pkg_failed=1

  rm -rf "$tmp_dir"
  return "$pkg_failed"
}

self_test() {
  local fixtures pass=0 fail=0
  fixtures=$(mktemp -d)

  make_fixture() { # <dir> <readme content> [files-json] [package name]
    local d="$fixtures/$1"
    mkdir -p "$d"
    printf '{"name":"%s","version":"0.0.0","license":"UNLICENSED"%s}\n' \
      "${4:-leakcheck-fixture-$1}" "${3:+,\"files\":$3}" > "$d/package.json"
    printf '%s\n' "$2" > "$d/README.md"
    echo "$d"
  }
  expect() { # <expected 0|1> <label> <dir>
    local rc=0
    check_package_dir "$3" >/dev/null 2>&1 || rc=1
    if [ "$rc" = "$1" ]; then
      pass=$((pass + 1))
    else
      fail=$((fail + 1))
      echo "SELF-TEST FAIL: ${2} (expected exit ${1}, got ${rc})"
    fi
  }

  expect 0 "clean package passes"            "$(make_fixture clean 'A helpful public package.')"
  expect 0 "bare CCR service name passes"    "$(make_fixture ccr-ok 'Talks to the CCR service at ccr.p1.pantheon.io.')"
  expect 1 "expanded codename fails"         "$(make_fixture codename 'Backed by the collaborative content repository.')"
  expect 1 "architecture terms fail"         "$(make_fixture arch 'Stores CRDT state in Postgres via a Durable Object.')"
  expect 1 "ticket ref fails"                "$(make_fixture ticket 'Workaround for PCC-9999.')"
  expect 1 "workers.dev hostname fails"      "$(make_fixture host 'Deployed to foo.workers.dev for now.')"
  expect 1 "missing files entry fails"       "$(make_fixture nobuild 'Clean readme.' '["generated-dist/"]')"
  expect 1 "double-spaced codename fails"    "$(make_fixture spaced 'The Collaborative  Content Repository backs this.')"
  expect 1 "Cloudflare fails for normal pkg" "$(make_fixture cf 'Runs on Cloudflare.')"
  expect 0 "Cloudflare exemption honored"    "$(make_fixture cf-ok 'Backed by Cloudflare R2.' '' '@pantheon-systems/p1-media')"

  # Filenames are public on npmjs.com even when every file's CONTENT is clean.
  local fnleak
  fnleak=$(make_fixture fnleak 'Clean readme.')
  : > "$fnleak/PCC-9999-notes.txt"
  expect 1 "leaky filename fails" "$fnleak"

  # The fail-closed core: a leaky extraction that scan_extracted cannot see
  # must be an error, never a clean pass.
  local badroot="$fixtures/badroot"
  mkdir -p "$badroot/not-package"
  echo 'Uses Postgres. PCC-9999.' > "$badroot/not-package/README.md"
  if scan_extracted "$badroot" "badroot-fixture" "$CS_PATTERN" >/dev/null 2>&1; then
    fail=$((fail + 1))
    echo "SELF-TEST FAIL: unexpected tarball layout reported clean (fails open)"
  else
    pass=$((pass + 1))
  fi

  rm -rf "$fixtures"
  echo "Self-test: ${pass} passed, ${fail} failed."
  [ "$fail" -eq 0 ]
}

checked_count=0

if [ "${1:-}" = "--self-test" ]; then
  self_test
  exit
fi

failed=0
for pkg_dir in packages/*/; do
  check_package_dir "$pkg_dir" || failed=1
done

# Fail closed on an empty scan: run from the wrong directory (an unexpanded
# `packages/*/` glob included), "clean" would mean "scanned nothing".
if [ "$checked_count" -eq 0 ]; then
  echo "::error::No public packages were found to scan — wrong working directory? Refusing to report clean."
  exit 1
fi

if [ "$failed" -ne 0 ]; then
  echo "::error::One or more public packages ship internal-only terms — fix the source (see errors above) and rebuild before publishing."
  exit 1
fi

echo "No internal-architecture leaks found in any public package tarball."
