/**
 * Catch-all route that renders user-facing pages generated by Puck.
 */

import { cache } from "react";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import {
  loadRemoteDatasourceContext,
  extractReferencedDatasourceIds,
  resolveDataTemplates,
  pagePathFromCatchAllSegments,
} from "@pantheon-systems/puck-css/server";
import {
  createCssQueryFetchers,
  loadPublishedPage,
  loadRouteTemplateKeys,
} from "@pantheon-systems/p1-next-sdk/server";
import { REMOTE_DATASOURCE_FETCHERS } from "../../lib/remote-datasource-fetchers";
import { ContentUnavailable } from "../../components/content-unavailable";
import { resolvePageMetadata } from "../../lib/page-seo";
import { Client } from "./client";

const getCcrQueryFetchers = cache(() => createCssQueryFetchers());

// Document namespaces that live alongside pages but are never routable.
const INTERNAL_PATH_PREFIXES = ["/_registry", "/_redirects"];

// Lowercased to match the server, which normalizes document paths to lower case
// before looking them up — so /_Redirects/x resolves the same record as
// /_redirects/x and must be refused just the same.
function isInternalPath(path: string): boolean {
  const normalized = path.toLowerCase();
  return INTERNAL_PATH_PREFIXES.some(
    (prefix) => normalized === prefix || normalized.startsWith(`${prefix}/`),
  );
}

/**
 * Backstop only: publishing calls revalidatePath for the affected routes, so
 * cached pages normally refresh the moment their content changes. This bounds
 * how long an edit made outside that path (a direct API write, a restored
 * branch) can stay stale.
 */
export const revalidate = 300;

/**
 * Empty on purpose. Routes are authored in P1, so there is nothing to enumerate
 * at build time — but declaring this is what marks the segment statically
 * renderable at all; without it every path here renders fully dynamically and
 * no response is ever cacheable. Unlisted paths render on first request and are
 * cached from then on (dynamicParams defaults to true).
 */
export function generateStaticParams(): { puckPath: string[] }[] {
  return [];
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}): Promise<Metadata> {
  const { puckPath = [] } = await params;
  const path = pagePathFromCatchAllSegments(puckPath);

  if (isInternalPath(path)) {
    return { title: "Not Found" };
  }

  const result = await loadPublishedPage(path);
  if (result.status === "missing") return { title: "Not Found" };
  if (result.status === "unavailable") {
    return { title: "Temporarily unavailable" };
  }
  return resolvePageMetadata({ pageData: result.data, path });
}

export default async function Page({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}) {
  const { puckPath = [] } = await params;
  const path = pagePathFromCatchAllSegments(puckPath);

  if (isInternalPath(path)) {
    notFound();
  }

  const result = await loadPublishedPage(path);

  // A real 404, so misses are not cached as successes now that this route is
  // statically renderable. An outage is deliberately not a 404 — that would
  // deindex published pages over a transient blip.
  if (result.status === "missing") {
    notFound();
  }
  if (result.status === "unavailable") {
    return <ContentUnavailable />;
  }

  const data = result.data;

  const [routeTemplateKeys, ccrQueryFetchers] = await Promise.all([
    loadRouteTemplateKeys(),
    getCcrQueryFetchers(),
  ]);
  const builtinFetchers = [...REMOTE_DATASOURCE_FETCHERS, ...ccrQueryFetchers];

  const referencedDatasourceIds = extractReferencedDatasourceIds(data);
  const context = await loadRemoteDatasourceContext({
    fetchImpl: fetch,
    pagePath: path,
    routeTemplateKeys,
    builtinFetchers,
    referencedDatasourceIds,
  });
  const resolvedData = await resolveDataTemplates(data, context);

  return (
    <Client
      data={resolvedData}
      pageMetadata={{
        route: path,
        documentName: data.root.props?.title as string | undefined,
        pageType: "page",
      }}
    />
  );
}
