/**
 * P1-backed PageStore — per-operation API calls.
 *
 * Each read/write/delete makes a real API call to the P1 backend.
 * No data is cached in memory — the backend is the source of truth.
 */

import type { SeoMetadata } from "@pantheon-systems/css-client";
import type { PageStore, PageSetOptions, DocumentMeta } from "./types";
import { getRequestAuthToken } from "./request-auth";

/**
 * Minimal subset of P1Client used by the store.
 * Declared here so consumers don't require a hard dependency on
 * @pantheon-systems/css-client — they pass in their own client instance.
 */
export interface P1StoreClient {
  documents: {
    list(siteId: string, branchId: string): Promise<{ id: string; path: string; templateId?: string | null }[]>;
    getByPath(siteId: string, path: string, branchId?: string): Promise<{ id: string; path: string }>;
    create(params: { siteId: string; branchId: string; path: string; templateId?: string; templateVersion?: number }): Promise<{ id: string; path: string }>;
    delete(siteId: string, branchId: string, documentId: string): Promise<void>;
  };
  versions: {
    getLatest(siteId: string, branchId: string, documentId: string): Promise<{ snapshot: Record<string, unknown> }>;
    create(siteId: string, params: { documentId: string; branchId: string; snapshot: Record<string, unknown> }): Promise<unknown>;
  };
  queries?: {
    list(siteId: string, branchId: string): Promise<{ name: string; datasource: string; sort: unknown[]; defaultLimit: number; maxLimit: number; includeMetadata: boolean; includeSnapshot: boolean; autoGenerated: boolean; version: number }[]>;
    getResults(siteId: string, branchId: string, queryName: string, params?: { limit?: number; offset?: number; includeMetadata?: boolean; includeSnapshot?: boolean }): Promise<{ items: unknown[]; returnedCount: number; query: unknown }>;
  };
}

/** Minimal subset of P1ContentClient used for published-only reads. */
export interface P1ContentClientInterface {
  getPage(path: string): Promise<{
    data: Record<string, unknown>;
    metadata?: SeoMetadata;
  } | null>;
}

export interface P1StoreConfig {
  client: P1StoreClient;
  /**
   * When provided, public reads (no auth token in context) use this client
   * which hits the content delivery endpoint and returns only published versions.
   * Editor reads (auth token present) always use the versions API.
   */
  contentClient?: P1ContentClientInterface;
  siteId: string;
  /**
   * Branch ID for authoring operations. When omitted, resolved lazily on the
   * first editor request via resolveBranchId. Not required for public reads —
   * those use contentClient which defaults to the main branch server-side.
   */
  branchId?: string;
  /**
   * Called on the first editor operation when branchId is not pre-configured.
   * Receives the bearer token from the active request context so branch
   * detection runs under the user's credentials, not the sat_ API key.
   */
  resolveBranchId?: (bearerToken: string) => Promise<string>;
  /** Factory to create a client with a specific bearer token (for user-auth writes). */
  createAuthClient?: (bearerToken: string) => P1StoreClient;
  /** When true, read operations also use the per-request auth client instead of the shared API-key client. */
  authenticatedReads?: boolean;
}

/**
 * Creates an async PageStore backed by a P1 API client.
 *
 * get/set/delete/has hit the API directly per call.
 * keys() is cached with a short TTL; on failure it serves the last successful
 * result and backs off for a cooldown before querying again.
 */
function toDocPath(path: string): string {
  if (path === "/") return "/";
  return path.startsWith("/") ? path.slice(1) : path;
}

function toStorePath(docPath: string): string {
  return docPath.startsWith("/") ? docPath : "/" + docPath;
}

const KEYS_CACHE_TTL_MS = 30_000;
const KEYS_MAX_RETRIES = 3;
const KEYS_RETRY_DELAY_MS = 500;
const KEYS_FAILURE_COOLDOWN_MS = 30_000;

/** A bad request will fail identically on every attempt — retrying only adds latency. */
function isBadRequest(err: unknown): boolean {
  return (
    typeof err === 'object' &&
    err !== null &&
    'status' in err &&
    (err as { status?: unknown }).status === 400
  );
}

async function withRetry<T>(
  fn: () => Promise<T>,
  retries: number,
  delayMs: number,
): Promise<T> {
  let lastErr: unknown;
  for (let i = 0; i <= retries; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      if (isBadRequest(err)) break;
      if (i < retries) {
        await new Promise((r) => setTimeout(r, delayMs * (i + 1)));
      }
    }
  }
  throw lastErr;
}

export function createP1PageStore(config: P1StoreConfig): PageStore {
  const { client, contentClient, siteId, createAuthClient, authenticatedReads } = config;

  let _keysCache: { promise: Promise<string[]>; ts: number; settled: boolean } | null = null;
  // Stale-while-error state: the last successful keys() result is kept and
  // served when a refresh fails, and after retries are exhausted no new
  // documents.list is issued until the cooldown expires. This stops DB
  // slowness from being amplified into a retry storm by page renders.
  let _lastGoodKeys: string[] | null = null;
  let _keysCooldownUntil = 0;
  let _resolvedBranchIdPromise: Promise<string> | null = null;

  // Returns the branch ID, resolving it lazily on the first editor request when
  // not pre-configured. Resolution uses the request's bearer token so it never
  // requires sat_ token access to the branches endpoint.
  function getBranchId(): Promise<string> {
    if (config.branchId) return Promise.resolve(config.branchId);
    if (!_resolvedBranchIdPromise) {
      const token = getRequestAuthToken();
      if (!token || !config.resolveBranchId) {
        return Promise.reject(
          new Error(
            "Branch ID required for editor operations: set p1BranchId in config or use an authenticated request.",
          ),
        );
      }
      _resolvedBranchIdPromise = config.resolveBranchId(token).catch((err: unknown) => {
        _resolvedBranchIdPromise = null;
        throw err;
      });
    }
    return _resolvedBranchIdPromise;
  }

  function requestClient(): P1StoreClient {
    const token = getRequestAuthToken();
    if (token && createAuthClient) {
      return createAuthClient(token);
    }
    return client;
  }

  function readClient(): P1StoreClient {
    return authenticatedReads ? requestClient() : client;
  }

  // Called after writes: forces the next keys() to refresh, including during a
  // failure cooldown (a deliberate user write outranks brownout backoff).
  function invalidateKeysCache(): void {
    _keysCache = null;
    _keysCooldownUntil = 0;
  }

  return {
    async get(path: string): Promise<unknown | undefined> {
      // Public rendering: no auth token in context — use content client which
      // returns only published versions via the content delivery endpoint.
      if (contentClient && !getRequestAuthToken()) {
        try {
          const result = await contentClient.getPage(toDocPath(path));
          const data = result?.data;
          if (!data) return undefined;
          // Fold SEO metadata onto root.props._seo so it flows through the Data
          // pipeline to generateMetadata. Public reads only (PCC-3407).
          if (result?.metadata) {
            const root = (data.root ?? {}) as Record<string, unknown>;
            const props = (root.props ?? {}) as Record<string, unknown>;
            return {
              ...data,
              root: { ...root, props: { ...props, _seo: result.metadata } },
            };
          }
          return data;
        } catch (err) {
          console.info("[css-store] get(%s) failed:", path, (err as Error).message);
          return undefined;
        }
      }
      // Editor context (auth token present) or no content client: return latest version.
      try {
        const branchId = await getBranchId();
        const rc = readClient();
        const doc = await rc.documents.getByPath(siteId, toDocPath(path), branchId);
        const version = await rc.versions.getLatest(siteId, branchId, doc.id);
        return version.snapshot;
      } catch (err) {
        console.info("[css-store] get(%s) failed:", path, (err as Error).message);
        return undefined;
      }
    },

    async set(path: string, value: unknown, options?: PageSetOptions): Promise<void> {
      const wc = requestClient();
      const dp = toDocPath(path);
      const branchId = await getBranchId();
      let docId: string;
      try {
        const existing = await readClient().documents.getByPath(siteId, dp, branchId);
        docId = existing.id;
      } catch {
        const createParams: { siteId: string; branchId: string; path: string; templateId?: string; templateVersion?: number } = {
          siteId, branchId, path: dp,
        };
        if (options?.templateId) {
          createParams.templateId = options.templateId;
        }
        if (options?.templateVersion != null) {
          createParams.templateVersion = options.templateVersion;
        }
        const created = await wc.documents.create(createParams);
        docId = created.id;
      }
      await wc.versions.create(siteId, {
        documentId: docId,
        branchId,
        snapshot: value as Record<string, unknown>,
      });
      invalidateKeysCache();
    },

    async delete(path: string): Promise<void> {
      try {
        const branchId = await getBranchId();
        const doc = await readClient().documents.getByPath(siteId, toDocPath(path), branchId);
        await requestClient().documents.delete(siteId, branchId, doc.id);
      } catch (err) {
        console.info("[css-store] delete(%s) — not found or failed:", path, (err as Error).message);
      }
      invalidateKeysCache();
    },

    async has(path: string): Promise<boolean> {
      try {
        await readClient().documents.getByPath(siteId, toDocPath(path), await getBranchId());
        return true;
      } catch (err) {
        console.info("[css-store] has(%s) — not found or failed:", path, (err as Error).message);
        return false;
      }
    },

    async keys(): Promise<string[]> {
      const now = Date.now();
      if (_keysCache) {
        if (now - _keysCache.ts < KEYS_CACHE_TTL_MS) {
          return _keysCache.promise;
        }
        if (!_keysCache.settled) {
          // A refresh is still in flight past the TTL (slow DB). Never pile a
          // second query on top of it — serve stale, or share the in-flight
          // promise when there's nothing stale to serve.
          return _lastGoodKeys ?? _keysCache.promise;
        }
      }
      if (now < _keysCooldownUntil) {
        return _lastGoodKeys ?? [];
      }
      // With a stale value to fall back on, fail fast (no retries) — the
      // caller is a page render and each retry re-drives the heaviest query.
      const retries = _lastGoodKeys ? 0 : KEYS_MAX_RETRIES;
      const promise = getBranchId()
        .then((branchId) => withRetry(
          () => readClient().documents.list(siteId, branchId),
          retries,
          KEYS_RETRY_DELAY_MS,
        ))
        .then((docs) => {
          const keys = docs.map((d) => toStorePath(d.path));
          _lastGoodKeys = keys;
          return keys;
        })
        .catch((err) => {
          console.error("[css-store] keys() failed:", (err as Error).message);
          _keysCache = null;
          _keysCooldownUntil = Date.now() + KEYS_FAILURE_COOLDOWN_MS;
          return _lastGoodKeys ?? [];
        });
      const entry = { promise, ts: now, settled: false };
      // The promise never rejects (the catch above returns a fallback).
      void promise.then(() => { entry.settled = true; });
      _keysCache = entry;
      return promise;
    },

    async listDocuments(): Promise<DocumentMeta[]> {
      try {
        const resolvedBranchId = await getBranchId();
        const docs = await withRetry(
          () => client.documents.list(siteId, resolvedBranchId),
          KEYS_MAX_RETRIES,
          KEYS_RETRY_DELAY_MS,
        );
        return docs.map((d) => ({
          path: toStorePath(d.path),
          templateId: d.templateId ?? undefined,
        }));
      } catch (err) {
        console.error("[css-store] listDocuments failed:", (err as Error).message);
        return [];
      }
    },
  };
}
