import { describe, it, expect, beforeEach, vi } from 'vitest';
import { QueriesEndpoint } from '../../src/endpoints/queries.js';
import type { BaseEndpoint } from '../../src/endpoints/base.js';
import type { Query, QueryResults } from '../../src/types.js';

function makeQuery(overrides: Partial<Query> = {}): Query {
  return {
    name: 'blog-post',
    datasource: 'blog-post',
    sort: [{ field: 'createdAt', direction: 'desc' }],
    defaultLimit: 20,
    maxLimit: 100,
    includeMetadata: true,
    includeSnapshot: false,
    autoGenerated: true,
    version: 1,
    ...overrides,
  };
}

function makeQueryResults(overrides: Partial<QueryResults> = {}): QueryResults {
  return {
    items: [
      {
        documentId: '5d8273b4-d25b-428a-b0f7-4d47619f3f20',
        path: 'blog/advanced-queries',
        createdAt: '2026-07-14T14:39:13.603Z',
      },
      {
        documentId: 'ed11ab8f-9939-497c-8130-ddfe2da2134d',
        path: 'blog/getting-started',
        createdAt: '2026-07-14T14:39:13.533Z',
      },
    ],
    returnedCount: 2,
    query: {
      name: 'blog-post',
      datasource: 'blog-post',
      sortedBy: 'createdAt:desc',
      appliedLimit: 10,
      appliedOffset: 0,
    },
    ...overrides,
  };
}

describe('QueriesEndpoint', () => {
  let baseEndpoint: BaseEndpoint;
  let endpoint: QueriesEndpoint;
  let mockRequest: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    mockRequest = vi.fn();
    baseEndpoint = { request: mockRequest } as unknown as BaseEndpoint;
    endpoint = new QueriesEndpoint(baseEndpoint);
  });

  describe('list', () => {
    it('makes GET request and returns query array', async () => {
      const mockQueries: Query[] = [
        makeQuery(),
        makeQuery({ name: 'landing-page', datasource: 'landing-page' }),
      ];

      mockRequest.mockResolvedValue({ queries: mockQueries });

      const result = await endpoint.list('site-123', 'branch-456');

      expect(mockRequest).toHaveBeenCalledWith(
        '/api/sites/site-123/branches/branch-456/queries',
        { method: 'GET' }
      );
      expect(result).toEqual(mockQueries);
      expect(result).toHaveLength(2);
    });
  });

  describe('get', () => {
    it('makes GET request with query name and returns single query', async () => {
      const mockQuery = makeQuery();

      mockRequest.mockResolvedValue(mockQuery);

      const result = await endpoint.get('site-123', 'branch-456', 'blog-post');

      expect(mockRequest).toHaveBeenCalledWith(
        '/api/sites/site-123/branches/branch-456/queries/blog-post',
        { method: 'GET' }
      );
      expect(result).toEqual(mockQuery);
      expect(result.sort[0]?.direction).toBe('desc');
    });
  });

  describe('delete', () => {
    it('makes DELETE request to remove a query', async () => {
      mockRequest.mockResolvedValue(undefined);

      await endpoint.delete('site-123', 'branch-456', 'blog-post');

      expect(mockRequest).toHaveBeenCalledWith(
        '/api/sites/site-123/branches/branch-456/queries/blog-post',
        { method: 'DELETE' }
      );
    });
  });

  describe('getResults', () => {
    it('makes GET request without query params when none provided', async () => {
      const results = makeQueryResults();
      mockRequest.mockResolvedValue(results);

      const result = await endpoint.getResults('site-123', 'branch-456', 'blog-post');

      expect(mockRequest).toHaveBeenCalledWith(
        '/api/sites/site-123/branches/branch-456/queries/blog-post/results',
        { method: 'GET' }
      );
      expect(result).toEqual(results);
      expect(result.items).toHaveLength(2);
    });

    it('appends limit and offset as query params', async () => {
      const results = makeQueryResults({ returnedCount: 5 });
      mockRequest.mockResolvedValue(results);

      const result = await endpoint.getResults('site-123', 'branch-456', 'blog-post', {
        limit: 5,
        offset: 10,
      });

      expect(mockRequest).toHaveBeenCalledWith(
        '/api/sites/site-123/branches/branch-456/queries/blog-post/results?limit=5&offset=10',
        { method: 'GET' }
      );
      expect(result.returnedCount).toBe(5);
    });

    it('appends only limit when offset is not provided', async () => {
      const results = makeQueryResults();
      mockRequest.mockResolvedValue(results);

      await endpoint.getResults('site-123', 'branch-456', 'blog-post', { limit: 10 });

      expect(mockRequest).toHaveBeenCalledWith(
        '/api/sites/site-123/branches/branch-456/queries/blog-post/results?limit=10',
        { method: 'GET' }
      );
    });

    it('appends only offset when limit is not provided', async () => {
      const results = makeQueryResults();
      mockRequest.mockResolvedValue(results);

      await endpoint.getResults('site-123', 'branch-456', 'blog-post', { offset: 20 });

      expect(mockRequest).toHaveBeenCalledWith(
        '/api/sites/site-123/branches/branch-456/queries/blog-post/results?offset=20',
        { method: 'GET' }
      );
    });

    it('returns items with metadata when includeMetadata is enabled', async () => {
      const results = makeQueryResults({
        items: [
          {
            documentId: 'doc-1',
            path: 'blog/hello',
            createdAt: '2026-07-14T00:00:00Z',
            metadata: { title: 'Hello World', author: 'Jane' },
          },
        ],
        returnedCount: 1,
      });
      mockRequest.mockResolvedValue(results);

      const result = await endpoint.getResults('site-123', 'branch-456', 'blog-post');

      expect(result.items[0]?.metadata).toEqual({ title: 'Hello World', author: 'Jane' });
    });
  });
});
