/**
 * Datasource Service Tests
 *
 * Tests for CRUD operations on datasource registry documents.
 * Datasources are stored at `_registry/datasources/{name}` and define
 * WHERE data comes from (a local content type template reference).
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { LocalDatasourceSnapshot } from '../../src/types/datasource';

vi.mock('../../src/services/document-service', () => ({
  getDocumentByPath: vi.fn(),
}));

vi.mock('../../src/services/branch-document-service', () => ({
  listDocumentsOnBranch: vi.fn(),
  createDocumentOnBranch: vi.fn(),
  deleteDocumentOnBranch: vi.fn(),
}));

vi.mock('../../src/services/document-version-service', () => ({
  getLatestDocumentVersion: vi.fn(),
  getLatestDocumentVersionWithFallback: vi.fn(),
  getLatestVersionsForDocuments: vi.fn(),
}));

describe('datasource-service', () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  describe('getDatasource', () => {
    it('should return a datasource by name from the registry path', async () => {
      const { getDatasource } = await import('../../src/services/datasource-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      const snapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        description: 'Blog content type',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-ds-1',
        siteId: 'site-1',
        path: '_registry/datasources/blog',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1',
        documentId: 'doc-ds-1',
        branchId: 'branch-1',
        versionNumber: 1,
        snapshot,
        source: 'edit',
        createdById: 'system',
        createdByType: 'system',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      const result = await getDatasource('site-1', 'branch-1', 'blog');

      expect(result).not.toBeNull();
      expect(result?.type).toBe('local');
      expect(result?.name).toBe('blog');
      expect(result?.templateId).toBe('tpl-uuid-1');

      expect(docService.getDocumentByPath).toHaveBeenCalledWith(
        'site-1',
        '_registry/datasources/blog',
      );
    });

    it('should return null when datasource document does not exist', async () => {
      const { getDatasource } = await import('../../src/services/datasource-service');
      const docService = await import('../../src/services/document-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce(null);

      const result = await getDatasource('site-1', 'branch-1', 'nonexistent');

      expect(result).toBeNull();
    });

    it('should return null when version does not exist on the branch', async () => {
      const { getDatasource } = await import('../../src/services/datasource-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-ds-1',
        siteId: 'site-1',
        path: '_registry/datasources/blog',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce(null);

      const result = await getDatasource('site-1', 'branch-1', 'blog');

      expect(result).toBeNull();
    });

    it('should fall back to main branch version when no version exists on feature branch', async () => {
      const { getDatasource } = await import('../../src/services/datasource-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      const snapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        description: 'Blog content type',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-ds-1',
        siteId: 'site-1',
        path: '_registry/datasources/blog',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersionWithFallback).mockResolvedValueOnce({
        version: {
          id: 'ver-main-1',
          documentId: 'doc-ds-1',
          branchId: 'main-branch-1',
          versionNumber: 1,
          snapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        inherited: true,
      });

      const result = await getDatasource('site-1', 'feature-branch-1', 'blog', 'main-branch-1');

      expect(result).not.toBeNull();
      expect(result?.name).toBe('blog');
      expect(result?.templateId).toBe('tpl-uuid-1');

      expect(versionService.getLatestDocumentVersionWithFallback).toHaveBeenCalledWith(
        'doc-ds-1',
        'feature-branch-1',
        'main-branch-1',
      );
    });

    it('should return branch version without fallback when it exists', async () => {
      const { getDatasource } = await import('../../src/services/datasource-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      const snapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-ds-1',
        siteId: 'site-1',
        path: '_registry/datasources/blog',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersionWithFallback).mockResolvedValueOnce({
        version: {
          id: 'ver-1',
          documentId: 'doc-ds-1',
          branchId: 'feature-branch-1',
          versionNumber: 2,
          snapshot,
          source: 'edit',
          createdById: 'user-1',
          createdByType: 'user',
          createdAt: '2026-02-01T00:00:00.000Z',
        },
        inherited: false,
      });

      const result = await getDatasource('site-1', 'feature-branch-1', 'blog', 'main-branch-1');

      expect(result).not.toBeNull();
      expect(result?.name).toBe('blog');
    });

    it('should return null when version exists on neither branch nor main', async () => {
      const { getDatasource } = await import('../../src/services/datasource-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-ds-1',
        siteId: 'site-1',
        path: '_registry/datasources/blog',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersionWithFallback).mockResolvedValueOnce(null);

      const result = await getDatasource('site-1', 'feature-branch-1', 'blog', 'main-branch-1');

      expect(result).toBeNull();
    });
  });

  describe('listDatasources', () => {
    it('should list all datasources on a branch by path prefix', async () => {
      const { listDatasources } = await import('../../src/services/datasource-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const versionService = await import('../../src/services/document-version-service');

      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        {
          id: 'doc-ds-1',
          siteId: 'site-1',
          path: '_registry/datasources/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
          inherited: false,
          isPublished: false,
        },
        {
          id: 'doc-ds-2',
          siteId: 'site-1',
          path: '_registry/datasources/events',
          createdAt: '2026-01-02T00:00:00.000Z',
          inherited: false,
          isPublished: false,
        },
      ]);

      const blogSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-1',
        autoGenerated: true,
        version: 1,
      };

      const eventsSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'events',
        templateName: 'Events',
        templateId: 'tpl-2',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([
        {
          id: 'ver-1',
          documentId: 'doc-ds-1',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: blogSnapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        {
          id: 'ver-2',
          documentId: 'doc-ds-2',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: eventsSnapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-02T00:00:00.000Z',
        },
      ]);

      const result = await listDatasources('site-1', 'branch-1');

      expect(result).toHaveLength(2);
      expect(result[0].name).toBe('blog');
      expect(result[1].name).toBe('events');

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({ pathPrefix: '_registry/datasources/' }),
      );
    });

    it('should skip datasources without versions on the branch', async () => {
      const { listDatasources } = await import('../../src/services/datasource-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const versionService = await import('../../src/services/document-version-service');

      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        {
          id: 'doc-ds-1',
          siteId: 'site-1',
          path: '_registry/datasources/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
          inherited: false,
          isPublished: false,
        },
      ]);

      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([]);

      const result = await listDatasources('site-1', 'branch-1');

      expect(result).toHaveLength(0);
    });

    it('should pass mainBranchId to listDocumentsOnBranch for COW fallback', async () => {
      const { listDatasources } = await import('../../src/services/datasource-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const versionService = await import('../../src/services/document-version-service');

      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([]);

      await listDatasources('site-1', 'feature-branch-1', 'main-branch-1');

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'feature-branch-1',
        expect.objectContaining({
          pathPrefix: '_registry/datasources/',
          mainBranchId: 'main-branch-1',
        }),
      );
    });
  });

  describe('createLocalDatasource', () => {
    it('should create a datasource document at the registry path', async () => {
      const { createLocalDatasource } = await import('../../src/services/datasource-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      vi.mocked(branchDocService.createDocumentOnBranch).mockResolvedValueOnce({
        document: {
          id: 'doc-ds-new',
          siteId: 'site-1',
          path: '_registry/datasources/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-new',
          documentId: 'doc-ds-new',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      const result = await createLocalDatasource({
        siteId: 'site-1',
        branchId: 'branch-1',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: true,
        createdById: 'system',
      });

      expect(result.document.path).toBe('_registry/datasources/blog');

      const createCall = vi.mocked(branchDocService.createDocumentOnBranch).mock.calls[0];
      const params = createCall[0];
      expect(params.path).toBe('_registry/datasources/blog');

      const snapshot = params.snapshot as LocalDatasourceSnapshot;
      expect(snapshot.type).toBe('local');
      expect(snapshot.name).toBe('blog');
      expect(snapshot.templateName).toBe('Blog');
      expect(snapshot.templateId).toBe('tpl-uuid-1');
      expect(snapshot.autoGenerated).toBe(true);
      expect(snapshot.version).toBe(1);
    });

    it('should reject names with invalid characters', async () => {
      const { createLocalDatasource } = await import('../../src/services/datasource-service');

      await expect(
        createLocalDatasource({
          siteId: 'site-1',
          branchId: 'branch-1',
          name: 'my datasource!',
          templateName: 'Blog',
          templateId: 'tpl-uuid-1',
          autoGenerated: false,
          createdById: 'user-1',
        }),
      ).rejects.toThrow();
    });

    it('should reject empty names', async () => {
      const { createLocalDatasource } = await import('../../src/services/datasource-service');

      await expect(
        createLocalDatasource({
          siteId: 'site-1',
          branchId: 'branch-1',
          name: '',
          templateName: 'Blog',
          templateId: 'tpl-uuid-1',
          autoGenerated: false,
          createdById: 'user-1',
        }),
      ).rejects.toThrow();
    });

    it('should accept valid alphanumeric-hyphen-underscore names', async () => {
      const { createLocalDatasource } = await import('../../src/services/datasource-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      vi.mocked(branchDocService.createDocumentOnBranch).mockResolvedValueOnce({
        document: {
          id: 'doc-ds-new',
          siteId: 'site-1',
          path: '_registry/datasources/blog-posts_v2',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-new',
          documentId: 'doc-ds-new',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'user-1',
          createdByType: 'user',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      const result = await createLocalDatasource({
        siteId: 'site-1',
        branchId: 'branch-1',
        name: 'blog-posts_v2',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: false,
        createdById: 'user-1',
      });

      expect(result.document.path).toBe('_registry/datasources/blog-posts_v2');
    });
  });

  describe('deleteDatasource', () => {
    it('should delete a datasource by name', async () => {
      const { deleteDatasource } = await import('../../src/services/datasource-service');
      const docService = await import('../../src/services/document-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-ds-1',
        siteId: 'site-1',
        path: '_registry/datasources/blog',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(branchDocService.deleteDocumentOnBranch).mockResolvedValueOnce(true);

      const result = await deleteDatasource({
        siteId: 'site-1',
        branchId: 'branch-1',
        name: 'blog',
        deletedById: 'user-1',
      });

      expect(result).toBe(true);
      expect(branchDocService.deleteDocumentOnBranch).toHaveBeenCalledWith(
        expect.objectContaining({
          documentId: 'doc-ds-1',
          branchId: 'branch-1',
        }),
      );
    });

    it('should return false when datasource does not exist', async () => {
      const { deleteDatasource } = await import('../../src/services/datasource-service');
      const docService = await import('../../src/services/document-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce(null);

      const result = await deleteDatasource({
        siteId: 'site-1',
        branchId: 'branch-1',
        name: 'nonexistent',
        deletedById: 'user-1',
      });

      expect(result).toBe(false);
    });
  });
});
