import { describe, expect, it, vi, beforeEach } from "vitest";

vi.mock("@pantheon-systems/puck-css/server", () => ({
  getSharedP1Client: vi.fn(),
  getSharedSiteId: vi.fn(),
  getSharedBranchId: vi.fn(),
  CSS_QUERY_ID_PREFIX: "templates.",
}));

import {
  getSharedP1Client,
  getSharedSiteId,
  getSharedBranchId,
} from "@pantheon-systems/puck-css/server";
import { createCssQueryFetchers } from "../css-query-fetchers";

const mockGetSharedP1Client = vi.mocked(getSharedP1Client);
const mockGetSharedSiteId = vi.mocked(getSharedSiteId);
const mockGetSharedBranchId = vi.mocked(getSharedBranchId);

function makeClient(queries?: {
  list: ReturnType<typeof vi.fn>;
  getResults: ReturnType<typeof vi.fn>;
}) {
  return { queries } as ReturnType<typeof getSharedP1Client>;
}

function makeQuery(name: string) {
  return {
    name,
    datasource: name,
    sort: [],
    filters: [],
    defaultLimit: 20,
    maxLimit: 100,
    includeMetadata: true,
    includeSnapshot: false,
    autoGenerated: true,
    version: 1,
  };
}

beforeEach(() => {
  vi.resetAllMocks();
});

describe("createCssQueryFetchers", () => {
  it("returns empty array when shared client is null", async () => {
    mockGetSharedP1Client.mockReturnValue(null);
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const fetchers = await createCssQueryFetchers();
    expect(fetchers).toEqual([]);
  });

  it("returns empty array when siteId is null", async () => {
    mockGetSharedP1Client.mockReturnValue(makeClient({ list: vi.fn(), getResults: vi.fn() }));
    mockGetSharedSiteId.mockReturnValue(null);
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const fetchers = await createCssQueryFetchers();
    expect(fetchers).toEqual([]);
  });

  it("returns empty array when branchId is null", async () => {
    mockGetSharedP1Client.mockReturnValue(makeClient({ list: vi.fn(), getResults: vi.fn() }));
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue(null);

    const fetchers = await createCssQueryFetchers();
    expect(fetchers).toEqual([]);
  });

  it("returns empty array when client has no queries property", async () => {
    mockGetSharedP1Client.mockReturnValue(makeClient());
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const fetchers = await createCssQueryFetchers();
    expect(fetchers).toEqual([]);
  });

  it("returns a fetcher for each query from queries.list()", async () => {
    const list = vi.fn().mockResolvedValue([makeQuery("news"), makeQuery("blog-post")]);
    mockGetSharedP1Client.mockReturnValue(makeClient({ list, getResults: vi.fn() }));
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const fetchers = await createCssQueryFetchers();
    expect(fetchers).toHaveLength(2);
    expect(fetchers.map((f) => f.id)).toEqual(["templates.news", "templates.blog-post"]);
  });

  it("fetcher calls getResults with correct params", async () => {
    const getResults = vi.fn().mockResolvedValue({ items: [], returnedCount: 0, query: {} });
    const list = vi.fn().mockResolvedValue([makeQuery("news")]);
    mockGetSharedP1Client.mockReturnValue(makeClient({ list, getResults }));
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const fetchers = await createCssQueryFetchers();
    const params = { searchParams: {}, urlParams: {}, savedPreviewParams: {}, fetchImpl: fetch };
    await fetchers[0].fetch(params);

    expect(getResults).toHaveBeenCalledWith("site-1", "branch-1", "news");
  });

  it("fetcher returns empty object on API error", async () => {
    const getResults = vi.fn().mockRejectedValue(new Error("API error"));
    const list = vi.fn().mockResolvedValue([makeQuery("news")]);
    mockGetSharedP1Client.mockReturnValue(makeClient({ list, getResults }));
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const fetchers = await createCssQueryFetchers();
    const params = { searchParams: {}, urlParams: {}, savedPreviewParams: {}, fetchImpl: fetch };
    const result = await fetchers[0].fetch(params);

    expect(result).toEqual({});
  });

  it("respects filterIds — only creates fetchers for matching query names", async () => {
    const list = vi.fn().mockResolvedValue([makeQuery("news"), makeQuery("blog-post"), makeQuery("event")]);
    mockGetSharedP1Client.mockReturnValue(makeClient({ list, getResults: vi.fn() }));
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const fetchers = await createCssQueryFetchers({ filterIds: new Set(["templates.news", "templates.event"]) });
    expect(fetchers).toHaveLength(2);
    expect(fetchers.map((f) => f.id)).toEqual(["templates.news", "templates.event"]);
  });

  it("deduplicates concurrent queries.list() calls for the same site/branch", async () => {
    const list = vi.fn().mockResolvedValue([makeQuery("news")]);
    mockGetSharedP1Client.mockReturnValue(makeClient({ list, getResults: vi.fn() }));
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const [a, b, c] = await Promise.all([
      createCssQueryFetchers(),
      createCssQueryFetchers(),
      createCssQueryFetchers(),
    ]);

    expect(list).toHaveBeenCalledTimes(1);
    expect(a).toHaveLength(1);
    expect(b).toHaveLength(1);
    expect(c).toHaveLength(1);
  });

  it("uses provided client override instead of shared client", async () => {
    const sharedGetResults = vi.fn();
    const overrideGetResults = vi.fn().mockResolvedValue({ items: [], returnedCount: 0, query: {} });
    const sharedList = vi.fn().mockResolvedValue([makeQuery("news")]);
    const overrideList = vi.fn().mockResolvedValue([makeQuery("news")]);

    mockGetSharedP1Client.mockReturnValue(makeClient({ list: sharedList, getResults: sharedGetResults }));
    mockGetSharedSiteId.mockReturnValue("site-1");
    mockGetSharedBranchId.mockReturnValue("branch-1");

    const overrideClient = makeClient({ list: overrideList, getResults: overrideGetResults });
    const fetchers = await createCssQueryFetchers({ client: overrideClient });

    expect(overrideList).toHaveBeenCalledWith("site-1", "branch-1");
    expect(sharedList).not.toHaveBeenCalled();

    const params = { searchParams: {}, urlParams: {}, savedPreviewParams: {}, fetchImpl: fetch };
    await fetchers[0].fetch(params);

    expect(overrideGetResults).toHaveBeenCalled();
    expect(sharedGetResults).not.toHaveBeenCalled();
  });
});
