/**
 * Datasource API Route Tests
 *
 * Tests for REST API endpoints for datasource operations.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { LocalDatasourceSnapshot } from '../../src/types/datasource';

vi.mock('../../src/services/datasource-service', () => ({
  getDatasource: vi.fn(),
  listDatasources: vi.fn(),
  createLocalDatasource: vi.fn(),
  deleteDatasource: vi.fn(),
}));

vi.mock('../../src/auth/authorization', () => ({
  assertPermission: vi.fn(),
  AuthorizationError: class AuthorizationError extends Error {
    constructor(message: string) {
      super(message);
      this.name = 'AuthorizationError';
    }
  },
}));

vi.mock('../../src/services/branch-service', () => ({
  getBranch: vi.fn(),
  getMainBranch: vi.fn(),
}));

describe('datasource-api', () => {
  beforeEach(async () => {
    vi.resetAllMocks();
    const branchService = await import('../../src/services/branch-service');
    vi.mocked(branchService.getBranch).mockResolvedValue({
      id: 'b1', siteId: 's1', name: 'main', isMain: true,
      createdAt: '', createdById: 'u1',
    } as never);
  });

  describe('handleDatasourceRoutes', () => {
    it('should list datasources on GET without name', async () => {
      const { handleDatasourceRoutes } = await import('../../src/routes/datasource-api');
      const datasourceService = await import('../../src/services/datasource-service');

      const snapshots: LocalDatasourceSnapshot[] = [
        {
          type: 'local',
          name: 'blog',
          templateName: 'Blog',
          templateId: 'tpl-1',
          autoGenerated: true,
          version: 1,
        },
      ];

      vi.mocked(datasourceService.listDatasources).mockResolvedValueOnce(snapshots);

      const request = new Request('http://localhost/api/sites/s1/branches/b1/datasources', {
        method: 'GET',
      });

      const response = await handleDatasourceRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.datasources).toHaveLength(1);
      expect(body.datasources[0].name).toBe('blog');
    });

    it('should get a single datasource on GET with name', async () => {
      const { handleDatasourceRoutes } = await import('../../src/routes/datasource-api');
      const datasourceService = await import('../../src/services/datasource-service');

      const snapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(snapshot);

      const request = new Request('http://localhost/api/sites/s1/branches/b1/datasources/blog', {
        method: 'GET',
      });

      const response = await handleDatasourceRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        datasourceName: 'blog',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.name).toBe('blog');
    });

    it('should return 404 when datasource not found', async () => {
      const { handleDatasourceRoutes } = await import('../../src/routes/datasource-api');
      const datasourceService = await import('../../src/services/datasource-service');

      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(null);

      const request = new Request('http://localhost/api/sites/s1/branches/b1/datasources/nope', {
        method: 'GET',
      });

      const response = await handleDatasourceRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        datasourceName: 'nope',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(404);
    });

    it('should return 400 when branchId is missing', async () => {
      const { handleDatasourceRoutes } = await import('../../src/routes/datasource-api');

      const request = new Request('http://localhost/api/sites/s1/datasources', {
        method: 'GET',
      });

      const response = await handleDatasourceRoutes(request, {
        siteId: 's1',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(400);
    });

    it('should return 405 for unsupported methods', async () => {
      const { handleDatasourceRoutes } = await import('../../src/routes/datasource-api');

      const request = new Request('http://localhost/api/sites/s1/branches/b1/datasources', {
        method: 'PATCH',
      });

      const response = await handleDatasourceRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(405);
    });

    it('should delete a datasource on DELETE', async () => {
      const { handleDatasourceRoutes } = await import('../../src/routes/datasource-api');
      const datasourceService = await import('../../src/services/datasource-service');

      vi.mocked(datasourceService.deleteDatasource).mockResolvedValueOnce(true);

      const request = new Request('http://localhost/api/sites/s1/branches/b1/datasources/blog', {
        method: 'DELETE',
      });

      const response = await handleDatasourceRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        datasourceName: 'blog',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(200);
    });
  });
});
