/**
 * Query API Route Tests
 *
 * Tests for REST API endpoints for query operations.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { QuerySnapshot } from '../../src/types/query';

vi.mock('../../src/services/query-service', () => ({
  getQuery: vi.fn(),
  listQueries: vi.fn(),
  createQuery: vi.fn(),
  deleteQuery: vi.fn(),
  executeQuery: vi.fn(),
  QueryNotFoundError: class QueryNotFoundError extends Error {
    constructor(name: string) {
      super(`Query "${name}" not found.`);
      this.name = 'QueryNotFoundError';
    }
  },
  DatasourceNotFoundError: class DatasourceNotFoundError extends Error {
    constructor(name: string) {
      super(`Datasource "${name}" not found.`);
      this.name = 'DatasourceNotFoundError';
    }
  },
}));

vi.mock('../../src/auth/authorization', () => ({
  assertPermission: vi.fn(),
  AuthorizationError: class AuthorizationError extends Error {
    constructor(message: string) {
      super(message);
      this.name = 'AuthorizationError';
    }
  },
}));

vi.mock('../../src/services/branch-service', () => ({
  getBranch: vi.fn(),
  getMainBranch: vi.fn(),
}));

const makeQuerySnapshot = (overrides: Partial<QuerySnapshot> = {}): QuerySnapshot => ({
  name: 'recent-posts',
  datasource: 'blog',
  sort: [{ field: 'createdAt', direction: 'desc' }],
  defaultLimit: 20,
  maxLimit: 100,
  includeMetadata: true,
  includeSnapshot: false,
  autoGenerated: true,
  version: 1,
  ...overrides,
});

describe('query-api', () => {
  beforeEach(async () => {
    vi.resetAllMocks();
    const branchService = await import('../../src/services/branch-service');
    vi.mocked(branchService.getBranch).mockResolvedValue({
      id: 'b1', siteId: 's1', name: 'main', isMain: true,
      createdAt: '', createdById: 'u1',
    } as never);
  });

  describe('handleQueryRoutes', () => {
    it('should list queries on GET without name', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');
      const queryService = await import('../../src/services/query-service');

      vi.mocked(queryService.listQueries).mockResolvedValueOnce([
        makeQuerySnapshot(),
      ]);

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.queries).toHaveLength(1);
    });

    it('should get a single query on GET with name', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');
      const queryService = await import('../../src/services/query-service');

      vi.mocked(queryService.getQuery).mockResolvedValueOnce(makeQuerySnapshot());

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries/recent-posts', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        queryName: 'recent-posts',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.name).toBe('recent-posts');
    });

    it('should return query results on GET with /results action', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');
      const queryService = await import('../../src/services/query-service');
      const branchService = await import('../../src/services/branch-service');

      vi.mocked(branchService.getBranch).mockResolvedValueOnce({
        id: 'b1', siteId: 's1', name: 'main', isMain: true,
        createdAt: '', createdById: 'u1',
      } as never);

      vi.mocked(queryService.executeQuery).mockResolvedValueOnce({
        items: [
          { documentId: 'doc-1', path: 'blog/post-1', createdAt: '2026-01-01T00:00:00.000Z' },
        ],
        returnedCount: 1,
        query: {
          name: 'recent-posts',
          datasource: 'blog',
          sortedBy: 'path',
          appliedLimit: 20,
          appliedOffset: 0,
        },
      });

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries/recent-posts/results?limit=10', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        queryName: 'recent-posts',
        action: 'results',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.items).toHaveLength(1);
    });

    it('should pass mainBranchId to executeQuery on a non-main branch', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');
      const queryService = await import('../../src/services/query-service');
      const branchService = await import('../../src/services/branch-service');

      vi.mocked(branchService.getBranch).mockResolvedValueOnce({
        id: 'feature-branch', siteId: 's1', name: 'feature', isMain: false,
        createdAt: '', createdById: 'u1',
      } as never);
      vi.mocked(branchService.getMainBranch).mockResolvedValueOnce({
        id: 'main-branch-id', siteId: 's1', name: 'main', isMain: true,
        createdAt: '', createdById: 'u1',
      } as never);

      vi.mocked(queryService.executeQuery).mockResolvedValueOnce({
        items: [],
        returnedCount: 0,
        query: {
          name: 'recent-posts',
          datasource: 'blog',
          sortedBy: 'path',
          appliedLimit: 20,
          appliedOffset: 0,
        },
      });

      const request = new Request('http://localhost/results', {
        method: 'GET',
      });

      await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'feature-branch',
        queryName: 'recent-posts',
        action: 'results',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(queryService.executeQuery).toHaveBeenCalledWith(
        expect.objectContaining({
          mainBranchId: 'main-branch-id',
        }),
      );
    });

    it('should return 404 when querying results for a non-existent query', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');
      const queryService = await import('../../src/services/query-service');
      const branchService = await import('../../src/services/branch-service');

      vi.mocked(branchService.getBranch).mockResolvedValueOnce({
        id: 'b1', siteId: 's1', name: 'main', isMain: true,
        createdAt: '', createdById: 'u1',
      } as never);

      vi.mocked(queryService.executeQuery).mockRejectedValueOnce(
        new queryService.QueryNotFoundError('nonexistent'),
      );

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries/nonexistent/results', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        queryName: 'nonexistent',
        action: 'results',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(404);
    });

    it('should return 400 when branchId is missing', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');

      const request = new Request('http://localhost/api/sites/s1/queries', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(400);
    });

    it('should delete a query on DELETE', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');
      const queryService = await import('../../src/services/query-service');

      vi.mocked(queryService.deleteQuery).mockResolvedValueOnce(true);

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries/recent-posts', {
        method: 'DELETE',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        queryName: 'recent-posts',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(200);
    });

    it('should return 404 when getBranch returns null for query results', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');
      const branchService = await import('../../src/services/branch-service');

      vi.mocked(branchService.getBranch).mockResolvedValueOnce(null);

      const request = new Request('http://localhost/api/sites/s1/branches/nonexistent/queries/recent-posts/results', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'nonexistent',
        queryName: 'recent-posts',
        action: 'results',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(404);
      const body = await response.json();
      expect(body.error).toBe('Branch not found');
    });

    it('should return 400 for negative limit', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries/recent-posts/results?limit=-1', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        queryName: 'recent-posts',
        action: 'results',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(400);
    });

    it('should reject limit exceeding maximum with 400', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries/recent-posts/results?limit=999', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        queryName: 'recent-posts',
        action: 'results',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(400);
      const body = await response.json();
      expect(body.error).toContain('limit cannot exceed');
    });

    it('should return 400 for negative offset', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries/recent-posts/results?offset=-1', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        queryName: 'recent-posts',
        action: 'results',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(400);
    });

    it('should return 400 for non-numeric limit', async () => {
      const { handleQueryRoutes } = await import('../../src/routes/query-api');

      const request = new Request('http://localhost/api/sites/s1/branches/b1/queries/recent-posts/results?limit=abc', {
        method: 'GET',
      });

      const response = await handleQueryRoutes(request, {
        siteId: 's1',
        branchId: 'b1',
        queryName: 'recent-posts',
        action: 'results',
        principal: { id: 'u1', type: 'user', dbUserId: 'u1' } as never,
      });

      expect(response.status).toBe(400);
    });
  });
});
