import baseConfig from '@pantheon-systems/eslint-config/base';
import prettierConfig from '@pantheon-systems/eslint-config/prettier';
import testsConfig from '@pantheon-systems/eslint-config/tests';

export default [
  ...baseConfig,
  ...prettierConfig,
  ...testsConfig,
  // template/ is generated by `pnpm build` and published standalone with its own config.
  { ignores: ['template/**'] },
];
