/**
 * Template Hooks
 *
 * Orchestrates auto-generation of datasources and queries
 * when a content type template is created. Both operations
 * are idempotent — if the datasource/query is already visible
 * from the branch (locally or inherited from main), creation
 * is skipped, and a racing duplicate is silently ignored.
 */

import { createLocalDatasource, datasourceExists } from './datasource-service';
import { createQuery, queryExists } from './query-service';
import { DuplicateDocumentPathError } from './errors';

export interface OnTemplateCreatedParams {
  siteId: string;
  branchId: string;
  templateName: string;
  templateId: string;
  createdById: string;
  /**
   * When provided, an existing datasource/query inherited from main counts
   * as already present and is not re-created on the branch. Without it a
   * branch would create a redundant local version 1 of a document main
   * already holds, guaranteeing a merge conflict on identical content.
   */
  mainBranchId?: string;
}

export interface OnTemplateCreatedResult {
  datasourceCreated: boolean;
  queryCreated: boolean;
  errors: string[];
}

export async function onTemplateCreated(
  params: OnTemplateCreatedParams,
): Promise<OnTemplateCreatedResult> {
  const result: OnTemplateCreatedResult = {
    datasourceCreated: false,
    queryCreated: false,
    errors: [],
  };

  try {
    const exists = await datasourceExists(
      params.siteId,
      params.branchId,
      params.templateName,
      params.mainBranchId,
    );
    if (!exists) {
      await createLocalDatasource({
        siteId: params.siteId,
        branchId: params.branchId,
        name: params.templateName,
        templateName: params.templateName,
        templateId: params.templateId,
        autoGenerated: true,
        createdById: params.createdById,
      });
    }
    result.datasourceCreated = true;
  } catch (error) {
    if (error instanceof DuplicateDocumentPathError) {
      result.datasourceCreated = true;
    } else {
      result.errors.push(`datasource: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  try {
    const exists = await queryExists(
      params.siteId,
      params.branchId,
      params.templateName,
      params.mainBranchId,
    );
    if (!exists) {
      await createQuery({
        siteId: params.siteId,
        branchId: params.branchId,
        name: params.templateName,
        datasource: params.templateName,
        autoGenerated: true,
        createdById: params.createdById,
      });
    }
    result.queryCreated = true;
  } catch (error) {
    if (error instanceof DuplicateDocumentPathError) {
      result.queryCreated = true;
    } else {
      result.errors.push(`query: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  return result;
}
