# Collaborative State System - Local Environment
# 
# This configuration validates infrastructure patterns locally.
# Actual local services run via Docker Compose (see docker/docker-compose.local.yaml)
# Miniflare runs separately via `make worker-dev`
#
# Usage:
#   make tf-init ENV=local    # Initialize with -backend=false
#   make tf-plan ENV=local    # Validate configuration
#   make tf-apply ENV=local   # Generate .dev.vars file

terraform {
  required_version = ">= 1.6.0"

  # No remote backend for local development
  # Initialize with: terraform init -backend=false

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

# -----------------------------------------------------------------------------
# Local Variables
# -----------------------------------------------------------------------------

locals {
  environment = "local"
  project     = "collaborative-state-system"

  # Pantheon pan-* tagging convention (used in higher environments)
  default_tags = {
    "pan-service"     = "collaborative-state-system"
    "pan-team"        = "content-management"
    "pan-environment" = local.environment
    "pan-managed-by"  = "terraform"
  }

  # Service configuration - matches docker-compose.local.yaml
  postgres = {
    host     = "localhost"
    port     = 5432
    user     = "cssuser"
    password = "csspass"
    database = "cssdb"
  }

  firestore = {
    host       = "localhost"
    port       = 8080
    project_id = "local-css-project"
  }

  worker = {
    port = 8787
  }
}

# -----------------------------------------------------------------------------
# Database Module (local configuration)
# -----------------------------------------------------------------------------

module "database" {
  source = "../../modules/database"

  environment    = local.environment
  postgres_host  = local.postgres.host
  postgres_port  = local.postgres.port
  postgres_user  = local.postgres.user
  postgres_pass  = local.postgres.password
  postgres_db    = local.postgres.database
  
  tags = local.default_tags
}

# -----------------------------------------------------------------------------
# Workers Module (local configuration)
# -----------------------------------------------------------------------------

module "workers" {
  source = "../../modules/workers"

  environment          = local.environment
  worker_port          = local.worker.port
  firestore_project_id = local.firestore.project_id
  firestore_host       = "${local.firestore.host}:${local.firestore.port}"
  
  # Database connection from module output
  postgres_connection_string = module.database.connection_string
  
  tags = local.default_tags
}

# -----------------------------------------------------------------------------
# Generate .dev.vars for Miniflare
# -----------------------------------------------------------------------------

resource "local_file" "dev_vars" {
  filename        = "${path.module}/../../../workers/.dev.vars"
  file_permission = "0600"
  content         = <<-EOT
# Auto-generated by Terraform (ENV=local)
# DO NOT COMMIT - This file is gitignored
# Regenerate with: make tf-apply ENV=local

ENVIRONMENT=${local.environment}
LOG_LEVEL=debug

# PostgreSQL connection (Docker container)
POSTGRES_CONNECTION_STRING=${module.database.connection_string}

# Firestore emulator (Docker container)
FIRESTORE_PROJECT_ID=${local.firestore.project_id}
FIRESTORE_EMULATOR_HOST=${local.firestore.host}:${local.firestore.port}

# CORS origins for local development
CORS_ORIGINS=http://localhost:3000,http://localhost:8080,http://localhost:5173

# WebSocket configuration
WEBSOCKET_HEARTBEAT_INTERVAL=30000

# Document sync settings
DOCUMENT_SYNC_BATCH_SIZE=50
PRESENCE_TTL_SECONDS=120

# Mock Google credentials (local development only)
# In production, this comes from Vault via OIDC
GOOGLE_APPLICATION_CREDENTIALS={"type":"service_account","project_id":"${local.firestore.project_id}","private_key_id":"local-mock-key","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBglocal-dev-mock-key\n-----END PRIVATE KEY-----\n","client_email":"local-dev@${local.firestore.project_id}.iam.gserviceaccount.com","client_id":"000000000000"}
EOT
}

# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------

output "environment" {
  description = "Current environment"
  value       = local.environment
}

output "postgres_connection_string" {
  description = "PostgreSQL connection string"
  value       = module.database.connection_string
  sensitive   = true
}

output "firestore_emulator_host" {
  description = "Firestore emulator host:port"
  value       = "${local.firestore.host}:${local.firestore.port}"
}

output "worker_url" {
  description = "Local worker URL (run 'make worker-dev' to start)"
  value       = "http://localhost:${local.worker.port}"
}

output "dev_vars_path" {
  description = "Path to generated .dev.vars file"
  value       = abspath(local_file.dev_vars.filename)
}

output "services" {
  description = "Local service endpoints"
  value = {
    postgres  = "${local.postgres.host}:${local.postgres.port}"
    firestore = "${local.firestore.host}:${local.firestore.port}"
    worker    = "localhost:${local.worker.port}"
  }
}

output "next_steps" {
  description = "Instructions for starting local development"
  value       = <<-EOT
    
    Local environment configured. Next steps:
    
    1. Start Docker services:    make docker-up
    2. Start Miniflare worker:   make worker-dev
    
    Or start everything:         make dev
    
  EOT
}
