/**
 * Datasource/Query Lifecycle Tests
 *
 * End-to-end tests verifying the full lifecycle:
 * 1. Template creation triggers auto-generation of datasource + query
 * 2. Multiple queries against one datasource
 * 3. Query execution returns correct documents
 * 4. Pagination and limit enforcement
 * 5. Idempotent auto-generation
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { LocalDatasourceSnapshot } from '../../src/types/datasource';
import type { QuerySnapshot } from '../../src/types/query';
import { DuplicateDocumentPathError } from '../../src/services/document-types';

vi.mock('../../src/services/document-service', () => ({
  getDocumentByPath: vi.fn(),
}));

vi.mock('../../src/services/branch-document-service', () => ({
  listDocumentsOnBranch: vi.fn(),
  countDocumentsOnBranch: vi.fn(),
  createDocumentOnBranch: vi.fn(),
  deleteDocumentOnBranch: vi.fn(),
}));

vi.mock('../../src/services/document-version-service', () => ({
  getLatestDocumentVersion: vi.fn(),
  getLatestVersionsForDocuments: vi.fn(),
}));

describe('datasource/query lifecycle', () => {
  beforeEach(async () => {
    vi.resetAllMocks();
    // resetAllMocks drops implementations, so this returns undefined unless a
    // test sets it — but its real signature is Promise<DocumentVersion[]>, and
    // executeQuery spreads the result.
    const versionService = await import('../../src/services/document-version-service');
    vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValue([]);
  });

  describe('template creation auto-generation', () => {
    it('should create datasource and query when onTemplateCreated is called', async () => {
      const { onTemplateCreated } = await import('../../src/services/template-hooks');
      const branchDocService = await import('../../src/services/branch-document-service');

      let createCallCount = 0;
      vi.mocked(branchDocService.createDocumentOnBranch).mockImplementation((params) => {
        createCallCount++;
        return Promise.resolve({
          document: {
            id: `doc-${String(createCallCount)}`,
            siteId: params.siteId,
            path: params.path,
            createdAt: '2026-01-01T00:00:00.000Z',
          },
          version: {
            id: `ver-${String(createCallCount)}`,
            documentId: `doc-${String(createCallCount)}`,
            branchId: params.branchId,
            versionNumber: 1,
            snapshot: params.snapshot ?? {},
            source: 'edit',
            createdById: params.createdById,
            createdByType: params.createdByType,
            createdAt: '2026-01-01T00:00:00.000Z',
          },
        });
      });

      await onTemplateCreated({
        siteId: 'site-1',
        branchId: 'branch-1',
        templateName: 'blog',
        templateId: 'tpl-uuid-1',
        createdById: 'user-1',
      });

      expect(branchDocService.createDocumentOnBranch).toHaveBeenCalledTimes(2);

      const firstCall = vi.mocked(branchDocService.createDocumentOnBranch).mock.calls[0][0];
      expect(firstCall.path).toBe('_registry/datasources/blog');
      const dsSnapshot = firstCall.snapshot as unknown as LocalDatasourceSnapshot;
      expect(dsSnapshot.type).toBe('local');
      expect(dsSnapshot.templateId).toBe('tpl-uuid-1');

      const secondCall = vi.mocked(branchDocService.createDocumentOnBranch).mock.calls[1][0];
      expect(secondCall.path).toBe('_registry/queries/blog');
      const qSnapshot = secondCall.snapshot as unknown as QuerySnapshot;
      expect(qSnapshot.datasource).toBe('blog');
      expect(qSnapshot.defaultLimit).toBe(20);
    });
  });

  describe('query execution through datasource', () => {
    it('should resolve datasource templateId and pass it to listDocumentsOnBranch', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      const querySnapshot: QuerySnapshot = {
        name: 'recent-posts',
        datasource: 'blog',
        sort: [{ field: 'createdAt', direction: 'desc' }],
        defaultLimit: 20,
        maxLimit: 100,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      };

      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-uuid-blog',
        autoGenerated: true,
        version: 1,
      };

      // Mock getQuery: doc lookup + version lookup
      vi.mocked(docService.getDocumentByPath)
        .mockResolvedValueOnce({
          id: 'doc-query',
          siteId: 'site-1',
          path: '_registry/queries/recent-posts',
          createdAt: '2026-01-01T00:00:00.000Z',
        })
        .mockResolvedValueOnce({
          id: 'doc-ds',
          siteId: 'site-1',
          path: '_registry/datasources/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
        });

      vi.mocked(versionService.getLatestDocumentVersion)
        .mockResolvedValueOnce({
          id: 'ver-q',
          documentId: 'doc-query',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: querySnapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        })
        .mockResolvedValueOnce({
          id: 'ver-ds',
          documentId: 'doc-ds',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: datasourceSnapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        });

      // Mock returns docs in DB-sorted order (createdAt desc, the query default)
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        {
          id: 'doc-2',
          siteId: 'site-1',
          path: 'blog/second-post',
          createdAt: '2026-01-02T00:00:00.000Z',
          inherited: false,
          isPublished: true,
          publishedVersionId: 'pv-1',
          publishedAt: '2026-01-02T12:00:00.000Z',
        },
        {
          id: 'doc-1',
          siteId: 'site-1',
          path: 'blog/hello-world',
          createdAt: '2026-01-01T00:00:00.000Z',
          inherited: false,
          isPublished: false,
        },
      ]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(2);

      const result = await executeQuery({
        siteId: 'site-1',
        branchId: 'branch-1',
        queryName: 'recent-posts',
      });

      expect(result.items).toHaveLength(2);
      expect(result.items[0].documentId).toBe('doc-2');
      expect(result.items[1].documentId).toBe('doc-1');
      expect(result.query.name).toBe('recent-posts');
      expect(result.query.datasource).toBe('blog');
      expect(result.query.appliedLimit).toBe(20);
      expect(result.query.appliedOffset).toBe(0);

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({
          templateId: 'tpl-uuid-blog',
          limit: 20,
          offset: 0,
          orderBy: { field: 'createdAt', direction: 'desc' },
        }),
      );
    });

    it('should enforce maxLimit when caller exceeds it', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      const querySnapshot: QuerySnapshot = {
        name: 'limited',
        datasource: 'blog',
        sort: [],
        defaultLimit: 10,
        maxLimit: 25,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: false,
        version: 1,
      };

      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath)
        .mockResolvedValueOnce({
          id: 'doc-q',
          siteId: 'site-1',
          path: '_registry/queries/limited',
          createdAt: '2026-01-01T00:00:00.000Z',
        })
        .mockResolvedValueOnce({
          id: 'doc-ds',
          siteId: 'site-1',
          path: '_registry/datasources/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
        });

      vi.mocked(versionService.getLatestDocumentVersion)
        .mockResolvedValueOnce({
          id: 'v1',
          documentId: 'doc-q',
          branchId: 'b1',
          versionNumber: 1,
          snapshot: querySnapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        })
        .mockResolvedValueOnce({
          id: 'v2',
          documentId: 'doc-ds',
          branchId: 'b1',
          versionNumber: 1,
          snapshot: datasourceSnapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        });

      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(0);

      const result = await executeQuery({
        siteId: 'site-1',
        branchId: 'b1',
        queryName: 'limited',
        limit: 500,
      });

      expect(result.query.appliedLimit).toBe(25);

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'b1',
        expect.objectContaining({ limit: 25 }),
      );
    });

    it('should pass offset to listDocumentsOnBranch for pagination', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      const querySnapshot: QuerySnapshot = {
        name: 'paginated',
        datasource: 'events',
        sort: [{ field: 'createdAt', direction: 'asc' }],
        defaultLimit: 10,
        maxLimit: 50,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      };

      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'events',
        templateName: 'Events',
        templateId: 'tpl-events',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath)
        .mockResolvedValueOnce({
          id: 'dq',
          siteId: 's1',
          path: '_registry/queries/paginated',
          createdAt: '2026-01-01T00:00:00.000Z',
        })
        .mockResolvedValueOnce({
          id: 'dds',
          siteId: 's1',
          path: '_registry/datasources/events',
          createdAt: '2026-01-01T00:00:00.000Z',
        });

      vi.mocked(versionService.getLatestDocumentVersion)
        .mockResolvedValueOnce({
          id: 'v1',
          documentId: 'dq',
          branchId: 'b1',
          versionNumber: 1,
          snapshot: querySnapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        })
        .mockResolvedValueOnce({
          id: 'v2',
          documentId: 'dds',
          branchId: 'b1',
          versionNumber: 1,
          snapshot: datasourceSnapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        });

      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(0);

      const result = await executeQuery({
        siteId: 's1',
        branchId: 'b1',
        queryName: 'paginated',
        limit: 10,
        offset: 30,
      });

      expect(result.query.appliedOffset).toBe(30);
      expect(result.query.appliedLimit).toBe(10);

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'b1',
        expect.objectContaining({
          templateId: 'tpl-events',
          limit: 10,
          offset: 30,
        }),
      );
    });
  });

  describe('multiple queries against one datasource', () => {
    it('should support different queries referencing the same datasource', async () => {
      const { getQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      const query1: QuerySnapshot = {
        name: 'recent-posts',
        datasource: 'blog',
        sort: [{ field: 'createdAt', direction: 'desc' }],
        defaultLimit: 5,
        maxLimit: 50,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      };

      const query2: QuerySnapshot = {
        name: 'all-posts',
        datasource: 'blog',
        sort: [{ field: 'path', direction: 'asc' }],
        defaultLimit: 100,
        maxLimit: 100,
        includeMetadata: true,
        includeSnapshot: true,
        autoGenerated: false,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath)
        .mockResolvedValueOnce({
          id: 'q1',
          siteId: 's1',
          path: '_registry/queries/recent-posts',
          createdAt: '2026-01-01T00:00:00.000Z',
        })
        .mockResolvedValueOnce({
          id: 'q2',
          siteId: 's1',
          path: '_registry/queries/all-posts',
          createdAt: '2026-01-01T00:00:00.000Z',
        });

      vi.mocked(versionService.getLatestDocumentVersion)
        .mockResolvedValueOnce({
          id: 'v1',
          documentId: 'q1',
          branchId: 'b1',
          versionNumber: 1,
          snapshot: query1,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        })
        .mockResolvedValueOnce({
          id: 'v2',
          documentId: 'q2',
          branchId: 'b1',
          versionNumber: 1,
          snapshot: query2,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        });

      const result1 = await getQuery('s1', 'b1', 'recent-posts');
      const result2 = await getQuery('s1', 'b1', 'all-posts');

      expect(result1?.datasource).toBe('blog');
      expect(result2?.datasource).toBe('blog');

      expect(result1?.defaultLimit).toBe(5);
      expect(result2?.defaultLimit).toBe(100);

      expect(result1?.includeSnapshot).toBe(false);
      expect(result2?.includeSnapshot).toBe(true);
    });
  });

  describe('idempotent auto-generation', () => {
    it('should not fail when template hook is called twice', async () => {
      const { onTemplateCreated } = await import('../../src/services/template-hooks');
      const branchDocService = await import('../../src/services/branch-document-service');

      vi.mocked(branchDocService.createDocumentOnBranch).mockResolvedValueOnce({
        document: {
          id: 'd1',
          siteId: 's1',
          path: '_registry/datasources/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'v1',
          documentId: 'd1',
          branchId: 'b1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'system',
          createdByType: 'user',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      }).mockResolvedValueOnce({
        document: {
          id: 'd2',
          siteId: 's1',
          path: '_registry/queries/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'v2',
          documentId: 'd2',
          branchId: 'b1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'system',
          createdByType: 'user',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      await onTemplateCreated({
        siteId: 's1',
        branchId: 'b1',
        templateName: 'blog',
        templateId: 'tpl-1',
        createdById: 'u1',
      });

      vi.resetAllMocks();

      vi.mocked(branchDocService.createDocumentOnBranch).mockRejectedValueOnce(
        new DuplicateDocumentPathError('_registry/datasources/blog', 's1'),
      );

      const result = await onTemplateCreated({
        siteId: 's1',
        branchId: 'b1',
        templateName: 'blog',
        templateId: 'tpl-1',
        createdById: 'u1',
      });

      expect(result.datasourceCreated).toBe(true);
      expect(result.errors).toHaveLength(0);
    });
  });
});
