/**
 * Query Service Tests
 *
 * Tests for CRUD operations and execution of query registry documents.
 * Queries are stored at `_registry/queries/{name}` and define
 * WHAT to retrieve from a datasource (filters, sort, pagination).
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { QuerySnapshot } from '../../src/types/query';
import type { LocalDatasourceSnapshot } from '../../src/types/datasource';

vi.mock('../../src/services/document-service', () => ({
  getDocumentByPath: vi.fn(),
}));

vi.mock('../../src/services/branch-document-service', () => ({
  listDocumentsOnBranch: vi.fn(),
  countDocumentsOnBranch: vi.fn(),
  createDocumentOnBranch: vi.fn(),
  deleteDocumentOnBranch: vi.fn(),
}));

vi.mock('../../src/services/document-version-service', () => ({
  getLatestDocumentVersion: vi.fn(),
  getLatestDocumentVersionWithFallback: vi.fn(),
  getLatestVersionsForDocuments: vi.fn(),
}));

vi.mock('../../src/services/datasource-service', () => ({
  getDatasource: vi.fn(),
}));

const makeQuerySnapshot = (overrides: Partial<QuerySnapshot> = {}): QuerySnapshot => ({
  name: 'recent-posts',
  description: 'Recent blog posts',
  datasource: 'blog',
  sort: [{ field: 'createdAt', direction: 'desc' }],
  defaultLimit: 20,
  maxLimit: 100,
  includeMetadata: true,
  includeSnapshot: false,
  autoGenerated: true,
  version: 1,
  ...overrides,
});

describe('query-service', () => {
  beforeEach(async () => {
    vi.resetAllMocks();
    // resetAllMocks drops implementations, so this returns undefined unless a
    // test sets it — but its real signature is Promise<DocumentVersion[]>, and
    // executeQuery spreads the result.
    const versionService = await import('../../src/services/document-version-service');
    vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValue([]);
  });

  describe('getQuery', () => {
    it('should return a query by name from the registry path', async () => {
      const { getQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      const snapshot = makeQuerySnapshot();

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1',
        documentId: 'doc-q-1',
        branchId: 'branch-1',
        versionNumber: 1,
        snapshot,
        source: 'edit',
        createdById: 'system',
        createdByType: 'system',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      const result = await getQuery('site-1', 'branch-1', 'recent-posts');

      expect(result).not.toBeNull();
      expect(result?.name).toBe('recent-posts');
      expect(result?.datasource).toBe('blog');
      expect(result?.defaultLimit).toBe(20);

      expect(docService.getDocumentByPath).toHaveBeenCalledWith(
        'site-1',
        '_registry/queries/recent-posts',
      );
    });

    it('should return null when query document does not exist', async () => {
      const { getQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce(null);

      const result = await getQuery('site-1', 'branch-1', 'nonexistent');
      expect(result).toBeNull();
    });

    it('should fall back to main branch version when no version exists on feature branch', async () => {
      const { getQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      const snapshot = makeQuerySnapshot();

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersionWithFallback).mockResolvedValueOnce({
        version: {
          id: 'ver-main-1',
          documentId: 'doc-q-1',
          branchId: 'main-branch-1',
          versionNumber: 1,
          snapshot,
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        inherited: true,
      });

      const result = await getQuery('site-1', 'feature-branch-1', 'recent-posts', 'main-branch-1');

      expect(result).not.toBeNull();
      expect(result?.name).toBe('recent-posts');
      expect(result?.datasource).toBe('blog');

      expect(versionService.getLatestDocumentVersionWithFallback).toHaveBeenCalledWith(
        'doc-q-1',
        'feature-branch-1',
        'main-branch-1',
      );
    });

    it('should return branch version without fallback when it exists', async () => {
      const { getQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      const snapshot = makeQuerySnapshot();

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersionWithFallback).mockResolvedValueOnce({
        version: {
          id: 'ver-1',
          documentId: 'doc-q-1',
          branchId: 'feature-branch-1',
          versionNumber: 2,
          snapshot,
          source: 'edit',
          createdById: 'user-1',
          createdByType: 'user',
          createdAt: '2026-02-01T00:00:00.000Z',
        },
        inherited: false,
      });

      const result = await getQuery('site-1', 'feature-branch-1', 'recent-posts', 'main-branch-1');

      expect(result).not.toBeNull();
      expect(result?.name).toBe('recent-posts');
    });

    it('should return null when version exists on neither branch nor main', async () => {
      const { getQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersionWithFallback).mockResolvedValueOnce(null);

      const result = await getQuery('site-1', 'feature-branch-1', 'recent-posts', 'main-branch-1');

      expect(result).toBeNull();
    });
  });

  describe('listQueries', () => {
    it('should list all queries on a branch by path prefix', async () => {
      const { listQueries } = await import('../../src/services/query-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const versionService = await import('../../src/services/document-version-service');

      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        {
          id: 'doc-q-1',
          siteId: 'site-1',
          path: '_registry/queries/recent-posts',
          createdAt: '2026-01-01T00:00:00.000Z',
          inherited: false,
          isPublished: false,
        },
        {
          id: 'doc-q-2',
          siteId: 'site-1',
          path: '_registry/queries/featured-blogs',
          createdAt: '2026-01-02T00:00:00.000Z',
          inherited: false,
          isPublished: false,
        },
      ]);

      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([
        {
          id: 'ver-1',
          documentId: 'doc-q-1',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: makeQuerySnapshot({ name: 'recent-posts' }),
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        {
          id: 'ver-2',
          documentId: 'doc-q-2',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: makeQuerySnapshot({ name: 'featured-blogs', datasource: 'blog' }),
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-02T00:00:00.000Z',
        },
      ]);

      const result = await listQueries('site-1', 'branch-1');

      expect(result).toHaveLength(2);
      expect(result[0].name).toBe('recent-posts');
      expect(result[1].name).toBe('featured-blogs');

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({ pathPrefix: '_registry/queries/' }),
      );
    });

    it('should pass mainBranchId to listDocumentsOnBranch for COW fallback', async () => {
      const { listQueries } = await import('../../src/services/query-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const versionService = await import('../../src/services/document-version-service');

      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([]);

      await listQueries('site-1', 'feature-branch-1', 'main-branch-1');

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'feature-branch-1',
        expect.objectContaining({
          pathPrefix: '_registry/queries/',
          mainBranchId: 'main-branch-1',
        }),
      );
    });
  });

  describe('createQuery', () => {
    it('should create a query document at the registry path', async () => {
      const { createQuery } = await import('../../src/services/query-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      vi.mocked(branchDocService.createDocumentOnBranch).mockResolvedValueOnce({
        document: {
          id: 'doc-q-new',
          siteId: 'site-1',
          path: '_registry/queries/recent-posts',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-new',
          documentId: 'doc-q-new',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      const result = await createQuery({
        siteId: 'site-1',
        branchId: 'branch-1',
        name: 'recent-posts',
        datasource: 'blog',
        autoGenerated: true,
        createdById: 'system',
      });

      expect(result.document.path).toBe('_registry/queries/recent-posts');

      const createCall = vi.mocked(branchDocService.createDocumentOnBranch).mock.calls[0];
      const params = createCall[0];
      expect(params.path).toBe('_registry/queries/recent-posts');

      const snapshot = params.snapshot as QuerySnapshot;
      expect(snapshot.name).toBe('recent-posts');
      expect(snapshot.datasource).toBe('blog');
      expect(snapshot.defaultLimit).toBe(20);
      expect(snapshot.maxLimit).toBe(100);
      expect(snapshot.includeMetadata).toBe(true);
      expect(snapshot.includeSnapshot).toBe(false);
      expect(snapshot.autoGenerated).toBe(true);
    });

    it('should cap maxLimit at PAGINATION.MAX_LIMIT when exceeded', async () => {
      const { createQuery } = await import('../../src/services/query-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      vi.mocked(branchDocService.createDocumentOnBranch).mockResolvedValueOnce({
        document: {
          id: 'doc-q-new',
          siteId: 'site-1',
          path: '_registry/queries/recent-posts',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-new',
          documentId: 'doc-q-new',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      await createQuery({
        siteId: 'site-1',
        branchId: 'branch-1',
        name: 'recent-posts',
        datasource: 'blog',
        maxLimit: 500,
        autoGenerated: true,
        createdById: 'system',
      });

      const createCall = vi.mocked(branchDocService.createDocumentOnBranch).mock.calls[0];
      const snapshot = createCall[0].snapshot as QuerySnapshot;
      expect(snapshot.maxLimit).toBe(100);
    });

    it('should reject names with invalid characters', async () => {
      const { createQuery } = await import('../../src/services/query-service');

      await expect(
        createQuery({
          siteId: 'site-1',
          branchId: 'branch-1',
          name: 'my query!',
          datasource: 'blog',
          autoGenerated: false,
          createdById: 'user-1',
        }),
      ).rejects.toThrow();
    });

    it('should reject empty names', async () => {
      const { createQuery } = await import('../../src/services/query-service');

      await expect(
        createQuery({
          siteId: 'site-1',
          branchId: 'branch-1',
          name: '',
          datasource: 'blog',
          autoGenerated: false,
          createdById: 'user-1',
        }),
      ).rejects.toThrow();
    });

    it('should accept valid alphanumeric-hyphen-underscore names', async () => {
      const { createQuery } = await import('../../src/services/query-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      vi.mocked(branchDocService.createDocumentOnBranch).mockResolvedValueOnce({
        document: {
          id: 'doc-q-new',
          siteId: 'site-1',
          path: '_registry/queries/recent-posts_v2',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-new',
          documentId: 'doc-q-new',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'user-1',
          createdByType: 'user',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      const result = await createQuery({
        siteId: 'site-1',
        branchId: 'branch-1',
        name: 'recent-posts_v2',
        datasource: 'blog',
        autoGenerated: false,
        createdById: 'user-1',
      });

      expect(result.document.path).toBe('_registry/queries/recent-posts_v2');
    });
  });

  describe('deleteQuery', () => {
    it('should delete a query by name', async () => {
      const { deleteQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const branchDocService = await import('../../src/services/branch-document-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(branchDocService.deleteDocumentOnBranch).mockResolvedValueOnce(true);

      const result = await deleteQuery({
        siteId: 'site-1',
        branchId: 'branch-1',
        name: 'recent-posts',
        deletedById: 'user-1',
      });

      expect(result).toBe(true);
    });
  });

  describe('executeQuery', () => {
    it('should execute a query against its datasource and return results', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot();
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1',
        documentId: 'doc-q-1',
        branchId: 'branch-1',
        versionNumber: 1,
        snapshot: querySnapshot,
        source: 'edit',
        createdById: 'system',
        createdByType: 'system',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);

      // Mock returns docs in DB-sorted order (createdAt desc, the query default)
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        {
          id: 'doc-blog-2',
          siteId: 'site-1',
          path: 'blog/second-post',
          createdAt: '2026-01-02T00:00:00.000Z',
          inherited: false,
          isPublished: false,
        },
        {
          id: 'doc-blog-1',
          siteId: 'site-1',
          path: 'blog/first-post',
          createdAt: '2026-01-01T00:00:00.000Z',
          inherited: false,
          isPublished: false,
        },
      ]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(2);

      const result = await executeQuery({
        siteId: 'site-1',
        branchId: 'branch-1',
        queryName: 'recent-posts',
      });

      expect(result.items).toHaveLength(2);
      expect(result.totalCount).toBe(2);
      expect(result.items[0].documentId).toBe('doc-blog-2');
      expect(result.items[0].path).toBe('blog/second-post');
      expect(result.query.name).toBe('recent-posts');
      expect(result.query.datasource).toBe('blog');

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({
          templateId: 'tpl-uuid-1',
          limit: 20,
          orderBy: { field: 'createdAt', direction: 'desc' },
        }),
      );
    });

    it('should enforce maxLimit when caller provides a limit exceeding it', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot({ maxLimit: 50 });
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1',
        documentId: 'doc-q-1',
        branchId: 'branch-1',
        versionNumber: 1,
        snapshot: querySnapshot,
        source: 'edit',
        createdById: 'system',
        createdByType: 'system',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(0);

      const result = await executeQuery({
        siteId: 'site-1',
        branchId: 'branch-1',
        queryName: 'recent-posts',
        limit: 200,
      });

      expect(result.query.appliedLimit).toBe(50);

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({ limit: 50 }),
      );
    });

    it('should throw QueryNotFoundError when query does not exist', async () => {
      const { executeQuery, QueryNotFoundError } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce(null);

      await expect(
        executeQuery({
          siteId: 'site-1',
          branchId: 'branch-1',
          queryName: 'nonexistent',
        }),
      ).rejects.toThrow(QueryNotFoundError);
    });

    it('should throw DatasourceNotFoundError when datasource does not exist', async () => {
      const { executeQuery, DatasourceNotFoundError } = await import(
        '../../src/services/query-service'
      );
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot();

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1',
        documentId: 'doc-q-1',
        branchId: 'branch-1',
        versionNumber: 1,
        snapshot: querySnapshot,
        source: 'edit',
        createdById: 'system',
        createdByType: 'system',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(null);

      await expect(
        executeQuery({
          siteId: 'site-1',
          branchId: 'branch-1',
          queryName: 'recent-posts',
        }),
      ).rejects.toThrow(DatasourceNotFoundError);
    });

    it('should apply caller offset override', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot();
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1',
        siteId: 'site-1',
        path: '_registry/queries/recent-posts',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1',
        documentId: 'doc-q-1',
        branchId: 'branch-1',
        versionNumber: 1,
        snapshot: querySnapshot,
        source: 'edit',
        createdById: 'system',
        createdByType: 'system',
        createdAt: '2026-01-01T00:00:00.000Z',
      });

      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(0);

      const result = await executeQuery({
        siteId: 'site-1',
        branchId: 'branch-1',
        queryName: 'recent-posts',
        offset: 40,
      });

      expect(result.query.appliedOffset).toBe(40);

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({ offset: 40 }),
      );
    });

    it('should forward mainBranchId to listDocumentsOnBranch', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot();
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local',
        name: 'blog',
        templateName: 'Blog',
        templateId: 'tpl-uuid-1',
        autoGenerated: true,
        version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersionWithFallback).mockResolvedValueOnce({
        version: {
          id: 'ver-1', documentId: 'doc-q-1', branchId: 'feature-1',
          versionNumber: 1, snapshot: querySnapshot, source: 'edit',
          createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
        },
        inherited: false,
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(0);

      await executeQuery({
        siteId: 'site-1',
        branchId: 'feature-1',
        queryName: 'recent-posts',
        mainBranchId: 'main-branch-uuid',
      });

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'feature-1',
        expect.objectContaining({ mainBranchId: 'main-branch-uuid' }),
      );

      expect(datasourceService.getDatasource).toHaveBeenCalledWith(
        'site-1',
        'feature-1',
        'blog',
        'main-branch-uuid',
      );
    });

    it('should return returnedCount equal to items.length', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot();
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local', name: 'blog', templateName: 'Blog',
        templateId: 'tpl-uuid-1', autoGenerated: true, version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1', documentId: 'doc-q-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: querySnapshot, source: 'edit',
        createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        { id: 'd1', siteId: 'site-1', path: 'blog/a', createdAt: '', inherited: false, isPublished: false },
        { id: 'd2', siteId: 'site-1', path: 'blog/b', createdAt: '', inherited: false, isPublished: false },
        { id: 'd3', siteId: 'site-1', path: 'blog/c', createdAt: '', inherited: false, isPublished: false },
      ]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(10);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(result.returnedCount).toBe(3);
      expect(result.totalCount).toBe(10);
      expect(result.returnedCount).toBe(result.items.length);
    });

    it('should pass createdAt:desc orderBy to listDocumentsOnBranch when query sorts by createdAt desc', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot({
        sort: [{ field: 'createdAt', direction: 'desc' }],
      });
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local', name: 'blog', templateName: 'Blog',
        templateId: 'tpl-uuid-1', autoGenerated: true, version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1', documentId: 'doc-q-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: querySnapshot, source: 'edit',
        createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        { id: 'd2', siteId: 'site-1', path: 'blog/beta', createdAt: '2026-03-01T00:00:00.000Z', inherited: false, isPublished: false },
        { id: 'd3', siteId: 'site-1', path: 'blog/gamma', createdAt: '2026-02-01T00:00:00.000Z', inherited: false, isPublished: false },
        { id: 'd1', siteId: 'site-1', path: 'blog/alpha', createdAt: '2026-01-01T00:00:00.000Z', inherited: false, isPublished: false },
      ]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(3);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({
          orderBy: { field: 'createdAt', direction: 'desc' },
        }),
      );
      expect(result.items[0].documentId).toBe('d2');
      expect(result.items[1].documentId).toBe('d3');
      expect(result.items[2].documentId).toBe('d1');
      expect(result.query.sortedBy).toBe('createdAt:desc');
    });

    it('should pass path:asc orderBy to listDocumentsOnBranch when query sorts by path asc', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot({
        sort: [{ field: 'path', direction: 'asc' }],
      });
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local', name: 'blog', templateName: 'Blog',
        templateId: 'tpl-uuid-1', autoGenerated: true, version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1', documentId: 'doc-q-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: querySnapshot, source: 'edit',
        createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        { id: 'd2', siteId: 'site-1', path: 'blog/alpha', createdAt: '2026-01-02T00:00:00.000Z', inherited: false, isPublished: false },
        { id: 'd3', siteId: 'site-1', path: 'blog/beta', createdAt: '2026-01-03T00:00:00.000Z', inherited: false, isPublished: false },
        { id: 'd1', siteId: 'site-1', path: 'blog/gamma', createdAt: '2026-01-01T00:00:00.000Z', inherited: false, isPublished: false },
      ]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(3);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({
          orderBy: { field: 'path', direction: 'asc' },
        }),
      );
      expect(result.query.sortedBy).toBe('path:asc');
    });

    it('should pass first sort field as orderBy from multi-field sort config', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot({
        sort: [
          { field: 'createdAt', direction: 'asc' },
          { field: 'path', direction: 'desc' },
        ],
      });
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local', name: 'blog', templateName: 'Blog',
        templateId: 'tpl-uuid-1', autoGenerated: true, version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1', documentId: 'doc-q-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: querySnapshot, source: 'edit',
        createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(0);

      await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({
          orderBy: { field: 'createdAt', direction: 'asc' },
        }),
      );
    });

    it('should pass orderBy alongside limit and offset so sort applies before pagination', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot({
        sort: [{ field: 'createdAt', direction: 'desc' }],
        defaultLimit: 10,
      });
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local', name: 'blog', templateName: 'Blog',
        templateId: 'tpl-uuid-1', autoGenerated: true, version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1', documentId: 'doc-q-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: querySnapshot, source: 'edit',
        createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(0);

      await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
        limit: 5, offset: 10,
      });

      expect(branchDocService.listDocumentsOnBranch).toHaveBeenCalledWith(
        'branch-1',
        expect.objectContaining({
          limit: 5,
          offset: 10,
          orderBy: { field: 'createdAt', direction: 'desc' },
        }),
      );
    });

    it('should preserve DB order in returned items without re-sorting in memory', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot({
        sort: [{ field: 'createdAt', direction: 'desc' }],
      });
      const datasourceSnapshot: LocalDatasourceSnapshot = {
        type: 'local', name: 'blog', templateName: 'Blog',
        templateId: 'tpl-uuid-1', autoGenerated: true, version: 1,
      };

      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1', documentId: 'doc-q-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: querySnapshot, source: 'edit',
        createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);

      // DB returns docs already sorted by createdAt desc
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        { id: 'newest', siteId: 'site-1', path: 'blog/z-path', createdAt: '2026-06-01T00:00:00.000Z', inherited: false, isPublished: false },
        { id: 'middle', siteId: 'site-1', path: 'blog/a-path', createdAt: '2026-03-01T00:00:00.000Z', inherited: false, isPublished: false },
        { id: 'oldest', siteId: 'site-1', path: 'blog/m-path', createdAt: '2026-01-01T00:00:00.000Z', inherited: false, isPublished: false },
      ]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(3);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      // Items must preserve DB order — newest first, not re-sorted by path
      expect(result.items.map((i) => i.documentId)).toEqual(['newest', 'middle', 'oldest']);
    });
  });

  describe('extractMetadataFromSnapshot', () => {
    it('should extract public fields from root.props', async () => {
      const { extractMetadataFromSnapshot } = await import('../../src/services/query-service');
      const result = extractMetadataFromSnapshot({
        root: { props: { title: 'Hello', description: 'World' } },
        content: [],
      });
      expect(result).toEqual({ title: 'Hello', description: 'World' });
    });

    it('should strip internal fields prefixed with _', async () => {
      const { extractMetadataFromSnapshot } = await import('../../src/services/query-service');
      const result = extractMetadataFromSnapshot({
        root: { props: { title: 'Hello', _contentTypeTemplateId: 'abc', _pinMap: {} } },
      });
      expect(result).toEqual({ title: 'Hello' });
    });

    it('should return empty object when snapshot has no root', async () => {
      const { extractMetadataFromSnapshot } = await import('../../src/services/query-service');
      expect(extractMetadataFromSnapshot({ content: [] })).toEqual({});
    });

    it('should return empty object when root has no props', async () => {
      const { extractMetadataFromSnapshot } = await import('../../src/services/query-service');
      expect(extractMetadataFromSnapshot({ root: {} })).toEqual({});
    });

    it('should preserve non-string values', async () => {
      const { extractMetadataFromSnapshot } = await import('../../src/services/query-service');
      const result = extractMetadataFromSnapshot({
        root: { props: { title: 'Hi', count: 42, tags: ['a', 'b'], active: true } },
      });
      expect(result).toEqual({ title: 'Hi', count: 42, tags: ['a', 'b'], active: true });
    });
  });

  describe('executeQuery metadata/snapshot population', () => {
    const datasourceSnapshot: LocalDatasourceSnapshot = {
      type: 'local', name: 'blog', templateName: 'Blog',
      templateId: 'tpl-uuid-1', autoGenerated: true, version: 1,
    };

    const puckSnapshot = {
      root: { props: { title: 'Post One', _contentTypeTemplateId: 'tpl-uuid-1' } },
      content: [{ type: 'HeadingBlock', props: { id: 'h1', title: 'Post One' } }],
      zones: {},
    };

    function setupQueryMocks(
      versionService: Awaited<ReturnType<typeof import('../../src/services/document-version-service')>>,
      docService: Awaited<ReturnType<typeof import('../../src/services/document-service')>>,
      datasourceService: Awaited<ReturnType<typeof import('../../src/services/datasource-service')>>,
      branchDocService: Awaited<ReturnType<typeof import('../../src/services/branch-document-service')>>,
      queryOverrides: Partial<QuerySnapshot> = {},
    ): void {
      const querySnapshot = makeQuerySnapshot(queryOverrides);
      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersion).mockResolvedValueOnce({
        id: 'ver-1', documentId: 'doc-q-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: querySnapshot, source: 'edit',
        createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        {
          id: 'doc-blog-1', siteId: 'site-1', path: 'blog/first-post',
          createdAt: '2026-01-01T00:00:00.000Z', inherited: false, isPublished: false,
        },
      ]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(1);
    }

    it('should populate metadata when includeMetadata is true', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      setupQueryMocks(versionService, docService, datasourceService, branchDocService, {
        includeMetadata: true, includeSnapshot: false,
      });
      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([{
        id: 'v1', documentId: 'doc-blog-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: puckSnapshot, source: 'edit',
        createdById: 'user-1', createdByType: 'user', createdAt: '2026-01-01T00:00:00.000Z',
      }]);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(result.items[0].metadata).toEqual({ title: 'Post One' });
      expect(result.items[0].snapshot).toBeUndefined();
    });

    it('should skip metadata when includeMetadata is false', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      setupQueryMocks(versionService, docService, datasourceService, branchDocService, {
        includeMetadata: false, includeSnapshot: false,
      });

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(result.items[0].metadata).toBeUndefined();
      expect(versionService.getLatestVersionsForDocuments).not.toHaveBeenCalled();
    });

    it('should populate snapshot when includeSnapshot is true', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      setupQueryMocks(versionService, docService, datasourceService, branchDocService, {
        includeMetadata: false, includeSnapshot: true,
      });
      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([{
        id: 'v1', documentId: 'doc-blog-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: puckSnapshot, source: 'edit',
        createdById: 'user-1', createdByType: 'user', createdAt: '2026-01-01T00:00:00.000Z',
      }]);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(result.items[0].snapshot).toEqual(puckSnapshot);
      expect(result.items[0].metadata).toBeUndefined();
    });

    it('should populate both metadata and snapshot when both flags are true', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      setupQueryMocks(versionService, docService, datasourceService, branchDocService, {
        includeMetadata: true, includeSnapshot: true,
      });
      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([{
        id: 'v1', documentId: 'doc-blog-1', branchId: 'branch-1',
        versionNumber: 1, snapshot: puckSnapshot, source: 'edit',
        createdById: 'user-1', createdByType: 'user', createdAt: '2026-01-01T00:00:00.000Z',
      }]);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(result.items[0].metadata).toEqual({ title: 'Post One' });
      expect(result.items[0].snapshot).toEqual(puckSnapshot);
      expect(versionService.getLatestVersionsForDocuments).toHaveBeenCalledTimes(1);
    });

    it('should handle missing version gracefully', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      setupQueryMocks(versionService, docService, datasourceService, branchDocService, {
        includeMetadata: true,
      });
      vi.mocked(versionService.getLatestVersionsForDocuments).mockResolvedValueOnce([]);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'branch-1', queryName: 'recent-posts',
      });

      expect(result.items).toHaveLength(1);
      expect(result.items[0].metadata).toBeUndefined();
    });

    it('should fetch inherited document versions from mainBranchId', async () => {
      const { executeQuery } = await import('../../src/services/query-service');
      const docService = await import('../../src/services/document-service');
      const versionService = await import('../../src/services/document-version-service');
      const branchDocService = await import('../../src/services/branch-document-service');
      const datasourceService = await import('../../src/services/datasource-service');

      const querySnapshot = makeQuerySnapshot({ includeMetadata: true });
      vi.mocked(docService.getDocumentByPath).mockResolvedValueOnce({
        id: 'doc-q-1', siteId: 'site-1',
        path: '_registry/queries/recent-posts', createdAt: '2026-01-01T00:00:00.000Z',
      });
      vi.mocked(versionService.getLatestDocumentVersionWithFallback).mockResolvedValueOnce({
        version: {
          id: 'ver-1', documentId: 'doc-q-1', branchId: 'main-branch',
          versionNumber: 1, snapshot: querySnapshot, source: 'edit' as const,
          createdById: 'system', createdByType: 'system' as const, createdAt: '2026-01-01T00:00:00.000Z',
        },
        inherited: true,
      });
      vi.mocked(datasourceService.getDatasource).mockResolvedValueOnce(datasourceSnapshot);
      vi.mocked(branchDocService.listDocumentsOnBranch).mockResolvedValueOnce([
        {
          id: 'doc-local', siteId: 'site-1', path: 'blog/local',
          createdAt: '2026-01-02T00:00:00.000Z', inherited: false, isPublished: false,
        },
        {
          id: 'doc-inherited', siteId: 'site-1', path: 'blog/inherited',
          createdAt: '2026-01-01T00:00:00.000Z', inherited: true, isPublished: true,
        },
      ]);
      vi.mocked(branchDocService.countDocumentsOnBranch).mockResolvedValueOnce(2);

      vi.mocked(versionService.getLatestVersionsForDocuments)
        .mockResolvedValueOnce([{
          id: 'v-local', documentId: 'doc-local', branchId: 'feature-1',
          versionNumber: 1, snapshot: { root: { props: { title: 'Local Post' } }, content: [] },
          source: 'edit', createdById: 'u1', createdByType: 'user', createdAt: '2026-01-02T00:00:00.000Z',
        }])
        .mockResolvedValueOnce([{
          id: 'v-inherited', documentId: 'doc-inherited', branchId: 'main-branch',
          versionNumber: 3, snapshot: { root: { props: { title: 'Main Post' } }, content: [] },
          source: 'edit', createdById: 'u1', createdByType: 'user', createdAt: '2026-01-01T00:00:00.000Z',
        }]);

      const result = await executeQuery({
        siteId: 'site-1', branchId: 'feature-1', queryName: 'recent-posts',
        mainBranchId: 'main-branch',
      });

      expect(versionService.getLatestVersionsForDocuments).toHaveBeenCalledWith(
        ['doc-local'], 'feature-1',
      );
      expect(versionService.getLatestVersionsForDocuments).toHaveBeenCalledWith(
        ['doc-inherited'], 'main-branch',
      );

      const localItem = result.items.find((i) => i.documentId === 'doc-local');
      const inheritedItem = result.items.find((i) => i.documentId === 'doc-inherited');
      expect(localItem?.metadata).toEqual({ title: 'Local Post' });
      expect(inheritedItem?.metadata).toEqual({ title: 'Main Post' });
    });
  });
});
