/**
 * Template Hooks Tests
 *
 * Tests for auto-generation of datasources and queries
 * when a content type template is created.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { DuplicateDocumentPathError } from '../../src/services/document-types';

vi.mock('../../src/services/datasource-service', () => ({
  createLocalDatasource: vi.fn(),
}));

vi.mock('../../src/services/query-service', () => ({
  createQuery: vi.fn(),
}));

describe('template-hooks', () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  describe('onTemplateCreated', () => {
    it('should create a datasource and default query for the template', async () => {
      const { onTemplateCreated } = await import('../../src/services/template-hooks');
      const datasourceService = await import('../../src/services/datasource-service');
      const queryService = await import('../../src/services/query-service');

      vi.mocked(datasourceService.createLocalDatasource).mockResolvedValueOnce({
        document: {
          id: 'doc-ds-1',
          siteId: 'site-1',
          path: '_registry/datasources/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-ds-1',
          documentId: 'doc-ds-1',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      vi.mocked(queryService.createQuery).mockResolvedValueOnce({
        document: {
          id: 'doc-q-1',
          siteId: 'site-1',
          path: '_registry/queries/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-q-1',
          documentId: 'doc-q-1',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      const result = await onTemplateCreated({
        siteId: 'site-1',
        branchId: 'branch-1',
        templateName: 'blog',
        templateId: 'tpl-uuid-1',
        createdById: 'user-1',
      });

      expect(result.datasourceCreated).toBe(true);
      expect(result.queryCreated).toBe(true);
      expect(result.errors).toHaveLength(0);

      expect(datasourceService.createLocalDatasource).toHaveBeenCalledWith(
        expect.objectContaining({
          siteId: 'site-1',
          branchId: 'branch-1',
          name: 'blog',
          templateName: 'blog',
          templateId: 'tpl-uuid-1',
          autoGenerated: true,
        }),
      );

      expect(queryService.createQuery).toHaveBeenCalledWith(
        expect.objectContaining({
          siteId: 'site-1',
          branchId: 'branch-1',
          name: 'blog',
          datasource: 'blog',
          autoGenerated: true,
        }),
      );
    });

    it('should still create query when datasource already exists', async () => {
      const { onTemplateCreated } = await import('../../src/services/template-hooks');
      const datasourceService = await import('../../src/services/datasource-service');
      const queryService = await import('../../src/services/query-service');

      vi.mocked(datasourceService.createLocalDatasource).mockRejectedValueOnce(
        new DuplicateDocumentPathError('_registry/datasources/blog', 'site-1'),
      );
      vi.mocked(queryService.createQuery).mockResolvedValueOnce({
        document: {
          id: 'doc-q-1',
          siteId: 'site-1',
          path: '_registry/queries/blog',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-q-1',
          documentId: 'doc-q-1',
          branchId: 'branch-1',
          versionNumber: 1,
          snapshot: {},
          source: 'edit',
          createdById: 'system',
          createdByType: 'system',
          createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      const result = await onTemplateCreated({
        siteId: 'site-1',
        branchId: 'branch-1',
        templateName: 'blog',
        templateId: 'tpl-uuid-1',
        createdById: 'user-1',
      });

      expect(result.datasourceCreated).toBe(true);
      expect(result.queryCreated).toBe(true);
      expect(result.errors).toHaveLength(0);

      expect(datasourceService.createLocalDatasource).toHaveBeenCalled();
      expect(queryService.createQuery).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'blog',
          datasource: 'blog',
        }),
      );
    });

    it('should be fully idempotent — skip both if both already exist', async () => {
      const { onTemplateCreated } = await import('../../src/services/template-hooks');
      const datasourceService = await import('../../src/services/datasource-service');
      const queryService = await import('../../src/services/query-service');

      vi.mocked(datasourceService.createLocalDatasource).mockRejectedValueOnce(
        new DuplicateDocumentPathError('_registry/datasources/blog', 'site-1'),
      );
      vi.mocked(queryService.createQuery).mockRejectedValueOnce(
        new DuplicateDocumentPathError('_registry/queries/blog', 'site-1'),
      );

      const result = await onTemplateCreated({
        siteId: 'site-1',
        branchId: 'branch-1',
        templateName: 'blog',
        templateId: 'tpl-uuid-1',
        createdById: 'user-1',
      });

      expect(result.datasourceCreated).toBe(true);
      expect(result.queryCreated).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    it('should capture non-duplicate errors without throwing', async () => {
      const { onTemplateCreated } = await import('../../src/services/template-hooks');
      const datasourceService = await import('../../src/services/datasource-service');
      const queryService = await import('../../src/services/query-service');

      vi.mocked(datasourceService.createLocalDatasource).mockRejectedValueOnce(
        new Error('Database connection failed'),
      );
      vi.mocked(queryService.createQuery).mockResolvedValueOnce({
        document: {
          id: 'doc-q-1', siteId: 'site-1',
          path: '_registry/queries/blog', createdAt: '2026-01-01T00:00:00.000Z',
        },
        version: {
          id: 'ver-q-1', documentId: 'doc-q-1', branchId: 'branch-1',
          versionNumber: 1, snapshot: {}, source: 'edit',
          createdById: 'system', createdByType: 'system', createdAt: '2026-01-01T00:00:00.000Z',
        },
      });

      const result = await onTemplateCreated({
        siteId: 'site-1',
        branchId: 'branch-1',
        templateName: 'blog',
        templateId: 'tpl-uuid-1',
        createdById: 'user-1',
      });

      expect(result.datasourceCreated).toBe(false);
      expect(result.queryCreated).toBe(true);
      expect(result.errors).toHaveLength(1);
      expect(result.errors[0]).toContain('Database connection failed');
    });
  });
});
