import { defineTool } from '../shared/define-tools.functions.js';
import { formatError, formatResult } from '../shared/format-mcp-responses.functions.js';
import { BranchScopedInputSchema } from './shared-schemas.js';

export const listQueriesTool = defineTool({
  description:
    'List all queries on a workstream. Queries define WHAT to retrieve from a datasource (filters, sort, pagination). Use get_query_results to retrieve results.',
  inputSchema: BranchScopedInputSchema,
  annotations: { title: 'List queries', readOnlyHint: true },
  mutates: false,
  handler: async (ctx, input) => {
    try {
      const result = await ctx.apiClient.listQueries(input.site_id, input.branch_id);
      if (result.queries.length === 0) {
        return formatResult('No queries found on this workstream.');
      }
      const formatted = result.queries
        .map((q: Record<string, unknown>) => {
          const auto = q.autoGenerated === true ? ' [auto]' : '';
          const line = `datasource: ${String(q.datasource)}, limit: ${String(q.defaultLimit)}`;
          return `- ${String(q.name)}${auto}\n  ${line}`;
        })
        .join('\n');
      return formatResult(`Queries:\n${formatted}`);
    } catch (error) {
      return formatError(error);
    }
  },
});
