#!/usr/bin/env bash
# generate-dev-vars.sh
#
# Generates .dev.vars file for local Miniflare development.
# This is an alternative to using Terraform for quick setup.
#
# Usage: ./scripts/generate-dev-vars.sh

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

# Output file
DEV_VARS_FILE="workers/.dev.vars"

# Default configuration (matches docker/docker-compose.local.yaml)
POSTGRES_USER="${POSTGRES_USER:-cssuser}"
POSTGRES_PASS="${POSTGRES_PASS:-csspass}"
POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_DB="${POSTGRES_DB:-cssdb}"

echo -e "${YELLOW}Generating ${DEV_VARS_FILE}...${NC}"

# Create the file
cat > "$DEV_VARS_FILE" << EOF
# Local Development Environment Variables
# Auto-generated by scripts/generate-dev-vars.sh
# DO NOT COMMIT - This file is gitignored
#
# Regenerate with: make worker-generate-secrets
# Or use Terraform: make tf-apply ENV=local

ENVIRONMENT=local
LOG_LEVEL=debug

# PostgreSQL connection (Docker/Podman container)
POSTGRES_CONNECTION_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

# CORS origins for local development
CORS_ORIGINS=http://localhost:3000,http://localhost:3002,http://localhost:3005,http://localhost:5173,http://localhost:8080

# Internal API secret for DO-to-PostgreSQL sync
INTERNAL_SECRET=development-internal-secret

# Mock JWT secret (local development only)
MOCK_JWT_SECRET=local-dev-jwt-secret-do-not-use-in-production
EOF

# Set permissions (readable only by owner)
chmod 600 "$DEV_VARS_FILE"

echo -e "${GREEN}Generated ${DEV_VARS_FILE}${NC}"
echo ""
echo "Configuration:"
echo "  PostgreSQL: ${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
echo ""
echo "Start local development with: make dev"
