/**
 * Datasource type definitions.
 *
 * A datasource defines WHERE data comes from — a local content type
 * (template reference) or eventually a remote API endpoint.
 * Stored at `_registry/datasources/{name}`.
 */

export interface LocalDatasourceSnapshot {
  type: 'local';
  name: string;
  description?: string;
  templateName: string;
  templateId: string;
  autoGenerated: boolean;
  version: number;
}

export type DatasourceSnapshot = LocalDatasourceSnapshot;

export function parseDatasourceSnapshot(value: unknown): DatasourceSnapshot {
  if (value === null || typeof value !== 'object') {
    throw new Error('DatasourceSnapshot: expected an object');
  }
  const obj = value as Record<string, unknown>;
  if (obj.type !== 'local') {
    throw new Error(`DatasourceSnapshot: unsupported type "${String(obj.type)}"`);
  }
  if (typeof obj.name !== 'string') {
    throw new Error('DatasourceSnapshot: name must be a string');
  }
  if (obj.description !== undefined && typeof obj.description !== 'string') {
    throw new Error('DatasourceSnapshot: description must be a string');
  }
  if (typeof obj.templateName !== 'string') {
    throw new Error('DatasourceSnapshot: templateName must be a string');
  }
  if (typeof obj.templateId !== 'string') {
    throw new Error('DatasourceSnapshot: templateId must be a string');
  }
  if (typeof obj.autoGenerated !== 'boolean') {
    throw new Error('DatasourceSnapshot: autoGenerated must be a boolean');
  }
  if (typeof obj.version !== 'number') {
    throw new Error('DatasourceSnapshot: version must be a number');
  }
  return value as DatasourceSnapshot;
}
