name = "p1-media"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "p1-media"

[[services]]
binding = "CSS_SERVICE"
service = "collaborative-state-worker-sbx1"

[vars]
CSS_BASE_URL = "https://collaborative-state-worker-sbx1.chris-801.workers.dev"
