/**
 * Generated by `scripts/sync-sdk-version.mjs` from package.json. Do not edit.
 *
 * Run `pnpm --filter @pantheon-systems/css-client sync-version` to regenerate; `prebuild` and the
 * repo's `ci:version` do it automatically.
 */

/** Name half of `x-p1-sdk`. */
export const SDK_NAME = 'css-client';

/** Version half of `x-p1-sdk`, matching the published release. */
export const SDK_VERSION = '0.11.1';
