/**
 * Datasource Service
 *
 * CRUD operations for datasource registry documents.
 * Datasources define WHERE data comes from — a local content type
 * (template reference) or eventually a remote API endpoint.
 * Stored at `_registry/datasources/{name}`.
 */

import type { DatasourceSnapshot, LocalDatasourceSnapshot } from '../types/datasource';
import { parseDatasourceSnapshot } from '../types/datasource';
import { parseQuerySnapshot } from '../types/query';
import type { CreateDocumentOnBranchResult } from './document-types';
import { getDocumentByPath } from './document-service';
import { listDocumentsOnBranch, createDocumentOnBranch, deleteDocumentOnBranch } from './branch-document-service';
import { getLatestDocumentVersion, getLatestDocumentVersionWithFallback, getLatestVersionsForDocuments } from './document-version-service';

const DATASOURCE_PATH_PREFIX = '_registry/datasources/';
const NAME_PATTERN = /^[a-zA-Z0-9_-]+$/;

export interface CreateLocalDatasourceParams {
  siteId: string;
  branchId: string;
  name: string;
  description?: string;
  templateName: string;
  templateId: string;
  autoGenerated: boolean;
  createdById: string;
}

export interface DeleteDatasourceParams {
  siteId: string;
  branchId: string;
  name: string;
  deletedById: string;
}

function datasourcePath(name: string): string {
  return `${DATASOURCE_PATH_PREFIX}${name}`;
}

export async function getDatasource(
  siteId: string,
  branchId: string,
  name: string,
  mainBranchId?: string,
): Promise<DatasourceSnapshot | null> {
  const doc = await getDocumentByPath(siteId, datasourcePath(name));
  if (doc === null) {
    return null;
  }

  if (mainBranchId !== undefined) {
    const fallback = await getLatestDocumentVersionWithFallback(doc.id, branchId, mainBranchId);
    if (fallback === null) {
      return null;
    }
    return parseDatasourceSnapshot(fallback.version.snapshot);
  }

  const version = await getLatestDocumentVersion(doc.id, branchId);
  if (version === null) {
    return null;
  }

  return parseDatasourceSnapshot(version.snapshot);
}

export async function listDatasources(
  siteId: string,
  branchId: string,
  mainBranchId?: string,
): Promise<DatasourceSnapshot[]> {
  const docs = await listDocumentsOnBranch(branchId, {
    pathPrefix: DATASOURCE_PATH_PREFIX,
    mainBranchId,
  });
  if (docs.length === 0) return [];

  const localIds = docs.filter((d) => !d.inherited).map((d) => d.id);
  const inheritedIds = docs.filter((d) => d.inherited).map((d) => d.id);

  const [localVersions, inheritedVersions] = await Promise.all([
    localIds.length > 0
      ? getLatestVersionsForDocuments(localIds, branchId)
      : [],
    inheritedIds.length > 0 && mainBranchId !== undefined
      ? getLatestVersionsForDocuments(inheritedIds, mainBranchId)
      : [],
  ]);

  const versionMap = new Map(
    [...localVersions, ...inheritedVersions].map((v) => [v.documentId, v]),
  );

  return docs
    .map((doc) => versionMap.get(doc.id))
    .filter((v): v is NonNullable<typeof v> => v !== undefined)
    .map((v) => parseDatasourceSnapshot(v.snapshot));
}

export async function createLocalDatasource(
  params: CreateLocalDatasourceParams,
): Promise<CreateDocumentOnBranchResult> {
  if (!NAME_PATTERN.test(params.name)) {
    throw new Error('Datasource name must contain only alphanumeric characters, hyphens, and underscores');
  }

  const snapshot: LocalDatasourceSnapshot = {
    type: 'local',
    name: params.name,
    description: params.description,
    templateName: params.templateName,
    templateId: params.templateId,
    autoGenerated: params.autoGenerated,
    version: 1,
  };

  return createDocumentOnBranch({
    siteId: params.siteId,
    branchId: params.branchId,
    path: datasourcePath(params.name),
    snapshot: snapshot as unknown as Record<string, unknown>,
    createdById: params.createdById,
    createdByType: 'user',
  });
}

export class DatasourceInUseError extends Error {
  public readonly name = 'DatasourceInUseError';

  constructor(
    public readonly datasourceName: string,
    public readonly referencingQueries: string[],
  ) {
    super(
      `Cannot delete datasource "${datasourceName}": referenced by queries: ${referencingQueries.join(', ')}`,
    );
    Object.setPrototypeOf(this, DatasourceInUseError.prototype);
  }
}

export async function deleteDatasource(
  params: DeleteDatasourceParams,
): Promise<boolean> {
  const doc = await getDocumentByPath(params.siteId, datasourcePath(params.name));
  if (doc === null) {
    return false;
  }

  const queryDocs = await listDocumentsOnBranch(params.branchId, {
    pathPrefix: '_registry/queries/',
  });

  if (queryDocs.length > 0) {
    const versions = await getLatestVersionsForDocuments(
      queryDocs.map((d) => d.id),
      params.branchId,
    );
    const referencingQueries: string[] = [];
    for (const v of versions) {
      try {
        const qs = parseQuerySnapshot(v.snapshot);
        if (qs.datasource === params.name) {
          referencingQueries.push(qs.name);
        }
      } catch {
        // skip unparseable snapshots
      }
    }
    if (referencingQueries.length > 0) {
      throw new DatasourceInUseError(params.name, referencingQueries);
    }
  }

  return deleteDocumentOnBranch({
    documentId: doc.id,
    branchId: params.branchId,
    deletedById: params.deletedById,
    deletedByType: 'user',
  });
}
