/**
 * Query Service
 *
 * CRUD and execution for query registry documents.
 * Queries define WHAT to retrieve from a datasource —
 * filters, sort, pagination. Stored at `_registry/queries/{name}`.
 * The View system references queries, not datasources directly.
 */

import type { QuerySnapshot, QuerySortField, ExecuteQueryResult, QueryResultItem } from '../types/query';
import { parseQuerySnapshot } from '../types/query';
import type { CreateDocumentOnBranchResult } from './document-types';
import { getDocumentByPath } from './document-service';
import { listDocumentsOnBranch, countDocumentsOnBranch, createDocumentOnBranch, deleteDocumentOnBranch } from './branch-document-service';
import { getLatestDocumentVersion, getLatestDocumentVersionWithFallback, getLatestVersionsForDocuments } from './document-version-service';
import { getDatasource } from './datasource-service';
import { PAGINATION } from '../routes/validation';

const QUERY_PATH_PREFIX = '_registry/queries/';
const NAME_PATTERN = /^[a-zA-Z0-9_-]+$/;

export class QueryNotFoundError extends Error {
  public readonly name = 'QueryNotFoundError';

  constructor(public readonly queryName: string) {
    super(`Query "${queryName}" not found.`);
    Object.setPrototypeOf(this, QueryNotFoundError.prototype);
  }
}

export class DatasourceNotFoundError extends Error {
  public readonly name = 'DatasourceNotFoundError';

  constructor(public readonly datasourceName: string) {
    super(`Datasource "${datasourceName}" not found.`);
    Object.setPrototypeOf(this, DatasourceNotFoundError.prototype);
  }
}

export interface CreateQueryParams {
  siteId: string;
  branchId: string;
  name: string;
  description?: string;
  datasource: string;
  sort?: QuerySortField[];
  defaultLimit?: number;
  maxLimit?: number;
  includeMetadata?: boolean;
  includeSnapshot?: boolean;
  autoGenerated: boolean;
  createdById: string;
}

export interface DeleteQueryParams {
  siteId: string;
  branchId: string;
  name: string;
  deletedById: string;
}

export interface ExecuteQueryParams {
  siteId: string;
  branchId: string;
  queryName: string;
  limit?: number;
  offset?: number;
  mainBranchId?: string;
}

function queryPath(name: string): string {
  return `${QUERY_PATH_PREFIX}${name}`;
}

export async function getQuery(
  siteId: string,
  branchId: string,
  name: string,
  mainBranchId?: string,
): Promise<QuerySnapshot | null> {
  const doc = await getDocumentByPath(siteId, queryPath(name));
  if (doc === null) {
    return null;
  }

  if (mainBranchId !== undefined) {
    const fallback = await getLatestDocumentVersionWithFallback(doc.id, branchId, mainBranchId);
    if (fallback === null) {
      return null;
    }
    return parseQuerySnapshot(fallback.version.snapshot);
  }

  const version = await getLatestDocumentVersion(doc.id, branchId);
  if (version === null) {
    return null;
  }

  return parseQuerySnapshot(version.snapshot);
}

export async function listQueries(
  _siteId: string,
  branchId: string,
  mainBranchId?: string,
): Promise<QuerySnapshot[]> {
  const docs = await listDocumentsOnBranch(branchId, {
    pathPrefix: QUERY_PATH_PREFIX,
    mainBranchId,
  });
  if (docs.length === 0) return [];

  const localIds = docs.filter((d) => !d.inherited).map((d) => d.id);
  const inheritedIds = docs.filter((d) => d.inherited).map((d) => d.id);

  const [localVersions, inheritedVersions] = await Promise.all([
    localIds.length > 0
      ? getLatestVersionsForDocuments(localIds, branchId)
      : [],
    inheritedIds.length > 0 && mainBranchId !== undefined
      ? getLatestVersionsForDocuments(inheritedIds, mainBranchId)
      : [],
  ]);

  const versionMap = new Map(
    [...localVersions, ...inheritedVersions].map((v) => [v.documentId, v]),
  );

  return docs
    .map((doc) => versionMap.get(doc.id))
    .filter((v): v is NonNullable<typeof v> => v !== undefined)
    .map((v) => parseQuerySnapshot(v.snapshot));
}

export async function createQuery(
  params: CreateQueryParams,
): Promise<CreateDocumentOnBranchResult> {
  if (!NAME_PATTERN.test(params.name)) {
    throw new Error('Query name must contain only alphanumeric characters, hyphens, and underscores');
  }

  const snapshot: QuerySnapshot = {
    name: params.name,
    description: params.description,
    datasource: params.datasource,
    sort: params.sort ?? [{ field: 'createdAt', direction: 'desc' }],
    defaultLimit: params.defaultLimit ?? 20,
    maxLimit: Math.min(params.maxLimit ?? 100, PAGINATION.MAX_LIMIT),
    includeMetadata: params.includeMetadata ?? true,
    includeSnapshot: params.includeSnapshot ?? false,
    autoGenerated: params.autoGenerated,
    version: 1,
  };

  return createDocumentOnBranch({
    siteId: params.siteId,
    branchId: params.branchId,
    path: queryPath(params.name),
    snapshot: snapshot as unknown as Record<string, unknown>,
    createdById: params.createdById,
    createdByType: 'user',
  });
}

export async function deleteQuery(
  params: DeleteQueryParams,
): Promise<boolean> {
  const doc = await getDocumentByPath(params.siteId, queryPath(params.name));
  if (doc === null) {
    return false;
  }

  return deleteDocumentOnBranch({
    documentId: doc.id,
    branchId: params.branchId,
    deletedById: params.deletedById,
    deletedByType: 'user',
  });
}

export function extractMetadataFromSnapshot(
  snapshot: Record<string, unknown>,
): Record<string, unknown> {
  const root = snapshot.root as { props?: Record<string, unknown> } | undefined;
  const props = root?.props;
  if (!props || typeof props !== 'object') return {};
  return Object.fromEntries(
    Object.entries(props).filter(([key]) => !key.startsWith('_')),
  );
}

export async function executeQuery(
  params: ExecuteQueryParams,
): Promise<ExecuteQueryResult> {
  const querySnapshot = await getQuery(params.siteId, params.branchId, params.queryName, params.mainBranchId);
  if (querySnapshot === null) {
    throw new QueryNotFoundError(params.queryName);
  }

  const datasource = await getDatasource(params.siteId, params.branchId, querySnapshot.datasource, params.mainBranchId);
  if (datasource === null) {
    throw new DatasourceNotFoundError(querySnapshot.datasource);
  }

  const appliedLimit = Math.max(
    1,
    Math.min(params.limit ?? querySnapshot.defaultLimit, querySnapshot.maxLimit),
  );
  const appliedOffset = Math.max(0, params.offset ?? 0);
  const primarySort = querySnapshot.sort[0];
  const SORTABLE_FIELDS = new Set<string>(['path', 'createdAt']);
  const sortField = primarySort !== undefined && SORTABLE_FIELDS.has(primarySort.field)
    ? (primarySort.field as 'path' | 'createdAt')
    : undefined;
  const [docs, totalCount] = await Promise.all([
    listDocumentsOnBranch(params.branchId, {
      templateId: datasource.templateId,
      limit: appliedLimit,
      offset: appliedOffset,
      mainBranchId: params.mainBranchId,
      orderBy: sortField !== undefined && primarySort !== undefined
        ? { field: sortField, direction: primarySort.direction }
        : undefined,
    }),
    countDocumentsOnBranch(params.branchId, {
      templateId: datasource.templateId,
      mainBranchId: params.mainBranchId,
    }),
  ]);

  const needVersions = querySnapshot.includeMetadata || querySnapshot.includeSnapshot;
  const versionMap = new Map<string, Record<string, unknown>>();

  if (needVersions && docs.length > 0) {
    const localIds = docs.filter((d) => !d.inherited).map((d) => d.id);
    const inheritedIds = docs.filter((d) => d.inherited).map((d) => d.id);

    const [localVersions, inheritedVersions] = await Promise.all([
      localIds.length > 0
        ? getLatestVersionsForDocuments(localIds, params.branchId)
        : [],
      inheritedIds.length > 0 && params.mainBranchId !== undefined && params.mainBranchId !== ''
        ? getLatestVersionsForDocuments(inheritedIds, params.mainBranchId)
        : [],
    ]);

    for (const v of [...localVersions, ...inheritedVersions]) {
      if (v.snapshot) {
        versionMap.set(v.documentId, v.snapshot);
      }
    }
  }

  const items: QueryResultItem[] = docs.map((doc) => {
    const item: QueryResultItem = {
      documentId: doc.id,
      path: doc.path,
      createdAt: doc.createdAt,
    };
    const snapshot = versionMap.get(doc.id);
    if (snapshot) {
      if (querySnapshot.includeMetadata) {
        item.metadata = extractMetadataFromSnapshot(snapshot);
      }
      if (querySnapshot.includeSnapshot) {
        item.snapshot = snapshot;
      }
    }
    return item;
  });

  const sortDescription = primarySort
    ? `${primarySort.field}:${primarySort.direction}`
    : 'path:asc';

  return {
    items,
    totalCount,
    returnedCount: items.length,
    query: {
      name: querySnapshot.name,
      datasource: querySnapshot.datasource,
      sortedBy: sortDescription,
      appliedLimit,
      appliedOffset,
    },
  };
}
