/**
 * Template Hooks
 *
 * Orchestrates auto-generation of datasources and queries
 * when a content type template is created. Both operations
 * are idempotent — if the datasource/query already exists,
 * the duplicate is silently ignored.
 */

import { createLocalDatasource } from './datasource-service';
import { createQuery } from './query-service';
import { DuplicateDocumentPathError } from './document-types';

export interface OnTemplateCreatedParams {
  siteId: string;
  branchId: string;
  templateName: string;
  templateId: string;
  createdById: string;
}

export interface OnTemplateCreatedResult {
  datasourceCreated: boolean;
  queryCreated: boolean;
  errors: string[];
}

export async function onTemplateCreated(
  params: OnTemplateCreatedParams,
): Promise<OnTemplateCreatedResult> {
  const result: OnTemplateCreatedResult = {
    datasourceCreated: false,
    queryCreated: false,
    errors: [],
  };

  try {
    await createLocalDatasource({
      siteId: params.siteId,
      branchId: params.branchId,
      name: params.templateName,
      templateName: params.templateName,
      templateId: params.templateId,
      autoGenerated: true,
      createdById: params.createdById,
    });
    result.datasourceCreated = true;
  } catch (error) {
    if (error instanceof DuplicateDocumentPathError) {
      result.datasourceCreated = true;
    } else {
      result.errors.push(`datasource: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  try {
    await createQuery({
      siteId: params.siteId,
      branchId: params.branchId,
      name: params.templateName,
      datasource: params.templateName,
      autoGenerated: true,
      createdById: params.createdById,
    });
    result.queryCreated = true;
  } catch (error) {
    if (error instanceof DuplicateDocumentPathError) {
      result.queryCreated = true;
    } else {
      result.errors.push(`query: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  return result;
}
