import { describe, it, expect } from "vitest";
import { cssQueriesToDatasourceDefinitions, CSS_QUERY_ID_PREFIX } from "../../data/css-queries/css-query-registry";

describe("cssQueriesToDatasourceDefinitions", () => {
  it("converts a single query to a RemoteDatasourceDefinition", () => {
    const queries = [
      {
        name: "blog-post",
        datasource: "blog-post",
        sort: [{ field: "createdAt", direction: "desc" as const }],

        defaultLimit: 20,
        maxLimit: 100,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      },
    ];

    const result = cssQueriesToDatasourceDefinitions(queries);

    expect(result).toHaveLength(1);
    const def = result[0];
    expect(def.id).toBe(`${CSS_QUERY_ID_PREFIX}blog-post`);
    expect(def.label).toBe("Blog Post");
    expect(def.resolution).toContain("content query");
  });

  it("converts multiple queries", () => {
    const queries = [
      {
        name: "blog-post",
        datasource: "blog-post",
        sort: [],

        defaultLimit: 20,
        maxLimit: 100,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      },
      {
        name: "landing-page",
        datasource: "landing-page",
        sort: [],

        defaultLimit: 10,
        maxLimit: 50,
        includeMetadata: false,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      },
    ];

    const result = cssQueriesToDatasourceDefinitions(queries);

    expect(result).toHaveLength(2);
    expect(result.map((d) => d.id)).toEqual([
      `${CSS_QUERY_ID_PREFIX}blog-post`,
      `${CSS_QUERY_ID_PREFIX}landing-page`,
    ]);
  });

  it("includes structural fields for query results", () => {
    const queries = [
      {
        name: "blog-post",
        datasource: "blog-post",
        sort: [],

        defaultLimit: 20,
        maxLimit: 100,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      },
    ];

    const result = cssQueriesToDatasourceDefinitions(queries);
    const fields = result[0].fields;
    const fieldPaths = fields.map((f) => f.path);

    expect(fieldPaths).toContain("items");
    expect(fieldPaths).toContain("returnedCount");
    expect(fieldPaths).toContain("query.name");
    expect(fieldPaths).toContain("query.sortedBy");
  });

  it("includes per-item document fields", () => {
    const queries = [
      {
        name: "blog-post",
        datasource: "blog-post",
        sort: [],

        defaultLimit: 20,
        maxLimit: 100,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      },
    ];

    const result = cssQueriesToDatasourceDefinitions(queries);
    const fieldPaths = result[0].fields.map((f) => f.path);

    expect(fieldPaths).toContain("items[].documentId");
    expect(fieldPaths).toContain("items[].path");
    expect(fieldPaths).toContain("items[].createdAt");
    expect(fieldPaths).toContain("items[].metadata");
    expect(fieldPaths).toContain("items[].metadata.title");
    expect(fieldPaths).toContain("items[].metadata.description");
    expect(fieldPaths).toContain("items[].snapshot");
  });

  it("converts kebab-case name to title-case label", () => {
    const queries = [
      {
        name: "product-landing-page",
        datasource: "product-landing-page",
        sort: [],

        defaultLimit: 20,
        maxLimit: 100,
        includeMetadata: false,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      },
    ];

    const result = cssQueriesToDatasourceDefinitions(queries);
    expect(result[0].label).toBe("Product Landing Page");
  });

  it("returns empty array for empty input", () => {
    expect(cssQueriesToDatasourceDefinitions([])).toEqual([]);
  });

  it("includes a description mentioning the datasource name", () => {
    const queries = [
      {
        name: "blog-post",
        datasource: "blog-post",
        sort: [],

        defaultLimit: 20,
        maxLimit: 100,
        includeMetadata: true,
        includeSnapshot: false,
        autoGenerated: true,
        version: 1,
      },
    ];

    const result = cssQueriesToDatasourceDefinitions(queries);
    expect(result[0].description).toContain("blog-post");
  });
});
